-- mod-devourer task 022: the Devourer's quests in the world (mounts). src/DevourerQuests.cpp.
-- Generated by tools/devourer_quests.py -- change the tool and run it again. Safe to run again.
-- Ids 9109000-9109899 (quests, credits, givers, objects), gameobject guids 9921000-9921999, creature guids 9922000-9922999.

DELETE FROM `gameobject` WHERE `guid` BETWEEN 9921000 AND 9921999;
DELETE FROM `creature` WHERE `guid` BETWEEN 9922000 AND 9922999;
DELETE FROM `gameobject_queststarter` WHERE `quest` BETWEEN 9109000 AND 9109399;
DELETE FROM `gameobject_questender` WHERE `quest` BETWEEN 9109000 AND 9109399;
DELETE FROM `creature_queststarter` WHERE `quest` BETWEEN 9109000 AND 9109399;
DELETE FROM `creature_questender` WHERE `quest` BETWEEN 9109000 AND 9109399;
DELETE FROM `gameobject_template` WHERE `entry` BETWEEN 9109000 AND 9109199;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 9109400 AND 9109899;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 9109400 AND 9109899;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (19, 20) AND `SourceEntry` BETWEEN 9109000 AND 9109399;
DELETE FROM `quest_offer_reward` WHERE `ID` BETWEEN 9109000 AND 9109399;
DELETE FROM `quest_request_items` WHERE `ID` BETWEEN 9109000 AND 9109399;
DELETE FROM `quest_template_addon` WHERE `ID` BETWEEN 9109000 AND 9109399;
DELETE FROM `quest_template` WHERE `ID` BETWEEN 9109000 AND 9109399;

-- --- Hagatha's lanterns (questgivers, one per region) and the witches' objects (goobers, one quest each) ---
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `AIName`, `ScriptName`, `VerifiedBuild`) VALUES
;

INSERT INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `Comment`) VALUES
;

-- --- credits: one per objective the core cannot count by itself (never spawned) -----------------------
DROP TEMPORARY TABLE IF EXISTS `devourer_tmp_ct`;
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 15384;
UPDATE `devourer_tmp_ct` SET `subname` = NULL, `faction` = 35, `npcflag` = 0, `unit_flags` = 33554434, `flags_extra` = 0, `AIName` = '', `ScriptName` = '', `VerifiedBuild` = 0;
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`) VALUES
;

-- --- the quests -------------------------------------------------------------------------------------
INSERT INTO `quest_template` (`ID`, `QuestType`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestInfoID`, `RewardXPDifficulty`, `RewardMoney`, `Flags`, `AllowableRaces`, `LogTitle`, `LogDescription`, `QuestDescription`, `AreaDescription`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGo2`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGo3`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount4`, `RequiredItemId1`, `RequiredItemCount1`, `RequiredItemId2`, `RequiredItemCount2`, `RequiredItemId3`, `RequiredItemCount3`, `RequiredItemId4`, `RequiredItemCount4`, `RewardItem1`, `RewardAmount1`, `RewardItem2`, `RewardAmount2`, `RewardItem3`, `RewardAmount3`, `RewardItem4`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemQuantity1`, `RewardChoiceItemID2`, `RewardChoiceItemQuantity2`, `RewardChoiceItemID3`, `RewardChoiceItemQuantity3`, `RewardChoiceItemID4`, `RewardChoiceItemQuantity4`, `RewardChoiceItemID5`, `RewardChoiceItemQuantity5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity6`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `TimeAllowed`, `VerifiedBuild`) VALUES
;
INSERT INTO `quest_template_addon` (`ID`, `AllowableClasses`, `PrevQuestID`) VALUES
;
INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`, `VerifiedBuild`) VALUES
;
INSERT INTO `quest_offer_reward` (`ID`, `Emote1`, `RewardText`, `VerifiedBuild`) VALUES
;
