-- Generated by tools/witch_sisters.py (task 010). Do not edit by hand: change the script and run it again.
-- The Hollowmoor sisters (Hagatha Hollowmoor, Wren Hollowmoor): the Devourer's trainers in the In-Between (map 35), their
-- cage and trappings, the three chores of the level-5 intro. Safe to run again; removed by uninstall/world.sql.

-- --- the 16 Devourer Trainers of task 006 are gone (tools/start_kit.py no longer makes them) ------------------
DELETE FROM `creature` WHERE `guid` BETWEEN 9910101 AND 9910116;
DELETE FROM `creature_default_trainer` WHERE `CreatureId` BETWEEN 9101200 AND 9101215;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 9101200 AND 9101215;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 9101200 AND 9101215;
DELETE FROM `gossip_menu_option` WHERE `MenuID` = 9101200;
DELETE FROM `gossip_menu` WHERE `MenuID` = 9101200;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (14, 15) AND `SourceGroup` = 9101200;
DELETE FROM `npc_text` WHERE `ID` IN (9101200, 9101201);

-- --- clean slate for this file's ids ---------------------------------------------------------------------------
DELETE FROM `creature` WHERE `guid` BETWEEN 9910200 AND 9910299;
DELETE FROM `gameobject` WHERE `guid` BETWEEN 9910200 AND 9910299;
DELETE FROM `creature_text` WHERE `CreatureID` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_template_addon` WHERE `entry` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_default_trainer` WHERE `CreatureId` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_queststarter` WHERE `id` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_questender` WHERE `id` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 9101300 AND 9101399;
DELETE FROM `gameobject_template_addon` WHERE `entry` BETWEEN 9101300 AND 9101399;
DELETE FROM `gameobject_template` WHERE `entry` BETWEEN 9101300 AND 9101399;
DELETE FROM `quest_offer_reward` WHERE `ID` BETWEEN 9101301 AND 9101303;
DELETE FROM `quest_request_items` WHERE `ID` BETWEEN 9101301 AND 9101303;
DELETE FROM `quest_template_addon` WHERE `ID` BETWEEN 9101301 AND 9101303;
DELETE FROM `quest_template` WHERE `ID` BETWEEN 9101301 AND 9101303;
DELETE FROM `gossip_menu_option` WHERE `MenuID` IN (9101300, 9101301);
DELETE FROM `gossip_menu` WHERE `MenuID` IN (9101300, 9101301);
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (14, 15) AND `SourceGroup` IN (9101300, 9101301);
DELETE FROM `npc_text` WHERE `ID` BETWEEN 9101300 AND 9101305;

-- --- the sisters ------------------------------------------------------------------------------------------------
-- Copies of a friendly stock NPC (made at install time, so no creature data is written here), as Devourer
-- Trainers, quest givers and gossip; the module's AI (ScriptName) answers the options it owns. Looks: a
-- stock creature's model each (Hagatha: Myranda the Hag 11872; Wren: Windfury Wind Witch 2963, a harpy).
DROP TEMPORARY TABLE IF EXISTS `devourer_tmp_ct`;
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 11872;
UPDATE `devourer_tmp_ct` SET `subname` = 'Devourer Trainer', `minlevel` = 80, `maxlevel` = 80, `faction` = 35,
    `npcflag` = 51, `unit_flags` = 768, `AIName` = '', `ScriptName` = 'npc_devourer_witch_sister', `lootid` = 0, `KillCredit1` = 0,
    `KillCredit2` = 0, `MovementType` = 0, `VerifiedBuild` = 0;
UPDATE `devourer_tmp_ct` SET `entry` = 9101300, `name` = 'Hagatha Hollowmoor', `gossip_menu_id` = 9101300;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101301, `name` = 'Wren Hollowmoor', `gossip_menu_id` = 9101301;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)
SELECT `m`.`entry`, 0, `ctm`.`CreatureDisplayID`, `ctm`.`DisplayScale`, 1, 0 FROM (
    SELECT 9101300 AS `entry`, 11872 AS `looks` UNION ALL SELECT 9101301 AS `entry`, 2963 AS `looks`
) AS `m` JOIN `creature_template_model` AS `ctm` ON `ctm`.`CreatureID` = `m`.`looks` AND `ctm`.`Idx` = 0;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES
(9101300, 9101200), (9101301, 9101200);

-- --- Wren's snacks (the first chore): rats, hostile, worth no experience; summoned into the cage by the module
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 4075;   -- Rat
UPDATE `devourer_tmp_ct` SET `entry` = 9101302, `name` = 'Wren''s Snack', `subname` = NULL, `minlevel` = 2, `maxlevel` = 3,
    `faction` = 14, `type` = 1, `npcflag` = 0, `unit_flags` = 0, `lootid` = 0, `skinloot` = 0, `pickpocketloot` = 0,
    `mingold` = 0, `maxgold` = 0, `ExperienceModifier` = 0, `DamageModifier` = 0.5, `AIName` = '', `ScriptName` = '',
    `KillCredit1` = 0, `KillCredit2` = 0, `VerifiedBuild` = 0;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)
SELECT 9101302, 0, `CreatureDisplayID`, `DisplayScale`, 1, 0 FROM `creature_template_model` WHERE `CreatureID` = 4075 AND `Idx` = 0;

-- --- the void under the cage: an unseen, unselectable creature wearing the Void Zone visual ------------------
-- --- and the three quest credits (never spawned; their names are what the quest log would show) ------------
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 15384;  -- OLDWorld Trigger
UPDATE `devourer_tmp_ct` SET `entry` = 9101303, `name` = 'The In-Between', `subname` = NULL, `faction` = 35, `npcflag` = 0,
    `unit_flags` = 33554434, `flags_extra` = 0, `AIName` = '', `ScriptName` = '', `VerifiedBuild` = 0;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101310, `name` = 'Snack devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101311, `name` = 'Roar at Wren';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101312, `name` = 'Hagatha''s tale heard';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`) VALUES
(9101303, 0, 11686, 1, 1, 0),
(9101310, 0, 11686, 1, 1, 0),
(9101311, 0, 11686, 1, 1, 0),
(9101312, 0, 11686, 1, 1, 0);   -- the invisible stalker model
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`) VALUES
(9101303, 0, 0, 0, 0, 0, 0, '64469');

-- --- spawns in the In-Between (map 35) ------------------------------------------------------------------
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `MovementType`, `Comment`) VALUES
(9910200, 9101300, 35, 1, 1, -100.4, 153.4, -40.11, 5.3271, 300, 0, 0, 'mod-devourer: Hagatha Hollowmoor'),
(9910201, 9101301, 35, 1, 1, -95.6, 153.4, -40.11, 4.0977, 300, 0, 0, 'mod-devourer: Wren Hollowmoor'),
(9910202, 9101303, 35, 1, 1, -98.0, 150.0, -40.28, 0, 300, 0, 0, 'mod-devourer: the void under the cage');

-- --- game objects: the Devourer's cage (a door: it opens), and the sisters' trappings -------------------------
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `AIName`, `ScriptName`, `VerifiedBuild`) VALUES
(9101300, 0, 4154, 'Wren''s Cage', '', '', '', 1.2, '', '', 0),
(9101301, 5, 1787, 'Wren''s Cage', '', '', '', 1.0, '', '', 0),
(9101302, 5, 216, 'Bubbling Cauldron', '', '', '', 1.0, '', '', 0),
(9101303, 5, 6038, 'Hagatha''s Lantern', '', '', '', 1.0, '', '', 0),
(9101304, 5, 187, 'Bookshelf', '', '', '', 1.0, '', '', 0),
(9101305, 5, 107, 'Book of Monster Tales', '', '', '', 1.0, '', '', 0),
(9101306, 5, 6328, 'Skull Pile', '', '', '', 1.0, '', '', 0),
(9101307, 5, 6406, 'Skull Candle', '', '', '', 1.0, '', '', 0),
(9101308, 5, 4152, 'Black Candle', '', '', '', 1.0, '', '', 0),
(9101309, 5, 465, 'Ritual Circle', '', '', '', 1.5, '', '', 0);
INSERT INTO `gameobject_template_addon` (`entry`, `faction`, `flags`, `mingold`, `maxgold`) VALUES
(9101300, 0, 16, 0, 0),
(9101301, 0, 0, 0, 0),
(9101302, 0, 0, 0, 0),
(9101303, 0, 0, 0, 0),
(9101304, 0, 0, 0, 0),
(9101305, 0, 0, 0, 0),
(9101306, 0, 0, 0, 0),
(9101307, 0, 0, 0, 0),
(9101308, 0, 0, 0, 0),
(9101309, 0, 0, 0, 0);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `Comment`) VALUES
(9910200, 9101309, 35, 1, 1, -98.0, 150.0, -40.23, 0.0000, 0, 0, 0.0, 1.0, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910201, 9101302, 35, 1, 1, -98.0, 157.0, -39.93, 4.7124, 0, 0, 0.707107, -0.707107, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910202, 9101303, 35, 1, 1, -101.9, 155.0, -40.03, 5.3748, 0, 0, 0.43873, -0.898619, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910203, 9101305, 35, 1, 1, -102.7, 152.6, -40.15, 5.7779, 0, 0, 0.249966, -0.968255, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910204, 9101304, 35, 1, 1, -105.5, 160.5, -40.21, 5.3326, 0, 0, 0.457582, -0.889168, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910205, 9101306, 35, 1, 1, -103.5, 157.5, -40.02, 5.3451, 0, 0, 0.452016, -0.89201, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910206, 9101307, 35, 1, 1, -100.6, 146.8, -40.27, 0.8885, 0, 0, 0.429772, 0.902938, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910207, 9101307, 35, 1, 1, -95.4, 146.8, -40.27, 2.2531, 0, 0, 0.902938, 0.429772, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910208, 9101308, 35, 1, 1, -101.6, 150.0, -40.28, 0.0000, 0, 0, 0.0, 1.0, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910209, 9101308, 35, 1, 1, -94.4, 150.0, -40.28, 3.1416, 0, 0, 1.0, 0.0, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910210, 9101301, 35, 1, 1, -92.0, 157.0, -39.93, 4.0038, 0, 0, 0.908513, -0.417857, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910211, 9101301, 35, 1, 1, -108.0, 160.0, -40.12, 5.4978, 0, 0, 0.382683, -0.92388, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910212, 9101301, 35, 1, 1, -88.0, 160.0, -40.11, 3.9270, 0, 0, 0.92388, -0.382683, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910213, 9101301, 35, 1, 1, -108.0, 140.0, -40.31, 0.7854, 0, 0, 0.382683, 0.92388, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910214, 9101301, 35, 1, 1, -88.0, 140.0, -40.24, 2.3562, 0, 0, 0.92388, 0.382683, 300, 0, 1, 'mod-devourer: the In-Between');

-- --- the three chores (class 10 only; each opens after the one before) ------------------------------------
INSERT INTO `quest_template` (`ID`, `QuestType`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestInfoID`, `RewardNextQuest`, `RewardXPDifficulty`, `Flags`, `AllowableRaces`, `LogTitle`, `LogDescription`, `QuestDescription`, `AreaDescription`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `VerifiedBuild`) VALUES
(9101301, 2, 5, 5, 0, 0, 9101302, 4, 0, 0, 'Feeding Time', 'Kill 3 of Wren''s snacks and devour one of them.', 'Fluffy! No, Snack. Project #9! You''ll answer to all of them, I''ve decided.$B$BFirst chore on the list: feeding time! I keep the snacks in the little cages, see? Squeaky ones. I toss them into your circle, you catch them. And don''t just bite them. EAT one. Properly, the way you do. I want to watch!', '', 'Return to Wren Hollowmoor.', 9101302, 9101310, 3, 1, '', 'Snack devoured', '', '', 0),
(9101302, 2, 5, 5, 0, 0, 0, 4, 0, 0, 'A Trick for Wren', 'Roar at Wren Hollowmoor.', 'Every good pet knows a trick. The toad knows ''sit''. The other toad knows ''sit'' too, but louder.$B$BYou, Fluffy, are going to ROAR. Big and scary, right at me. Go on! I''ll pretend to be frightened. I''m very good at it.', '', 'Return to Wren Hollowmoor.', 9101311, 0, 1, 0, 'Roar at Wren', '', '', '', 0),
(9101303, 2, 5, 5, 0, 0, 0, 5, 0, 0, 'What the Dark Remembers', 'Ask Hagatha Hollowmoor for the tale of the hungry thing, and listen to its end.', 'My sister teaches you tricks. I will teach you what you are.$B$BEvery village has a story about something that came out of the dark and ate until it became something else. Sit, hungry thing. Ask me for the tale, and listen to the end of it. The ones who do not listen end up in it.', '', 'Return to Hagatha Hollowmoor.', 9101312, 0, 1, 0, 'Hear Hagatha''s tale', '', '', '', 0);
INSERT INTO `quest_template_addon` (`ID`, `AllowableClasses`, `PrevQuestID`) VALUES
(9101301, 512, 0),
(9101302, 512, 9101301),
(9101303, 512, 9101302);
INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`, `VerifiedBuild`) VALUES
(9101301, 1, 1, 'Still squeaking in there? Somebody''s not done.', 0),
(9101302, 1, 1, 'I''m waiting! Rooooar. Like that, but you.', 0),
(9101303, 1, 1, 'The tale is not finished with you yet.', 0);
INSERT INTO `quest_offer_reward` (`ID`, `Emote1`, `RewardText`, `VerifiedBuild`) VALUES
(9101301, 1, 'Crunchy! Hagatha, did you see? It ate it whole! Well. Mostly whole.$B$BGold star, Snack. Next chore!', 0),
(9101302, 1, 'Eek! Ha! Oh, that was GOOD. That goes on the list of things you''re good at. It''s a short list. It''s a new list!$B$BNow go and sit nicely for Hagatha. She''s been dying to frighten you back.', 0),
(9101303, 1, 'Now you know the shape beneath all your shapes. Remember it when you wear someone else''s.$B$BWren, break the circle. Our little horror has lessons to carry into the world, and it will come back to us for more.', 0);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES
(9101301, 9101301), (9101301, 9101302), (9101300, 9101303);
INSERT INTO `creature_questender` (`id`, `quest`) VALUES
(9101301, 9101301), (9101301, 9101302), (9101300, 9101303);

-- --- what they say (creature_text; the module calls the groups at the right moments) ---------------------
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(9101301, 0, 0, 'Found you! Hold still, Snack. This tickles. Mostly.', 15, 0, 100, 0, 0, 0, 0, 0, 'Wren 0 (draft)'),
(9101300, 0, 0, 'Hush, sister. Let it wake slowly. The ones that wake fast bite the hand that feeds them.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 0 (draft)'),
(9101301, 1, 0, 'It''s awake! Hagatha, it''s AWAKE! Hello, hello, Project #9! Don''t smudge the circle, the chalk is new.', 12, 0, 100, 5, 0, 0, 0, 0, 'Wren 1 (draft)'),
(9101300, 1, 0, 'So. Another hungry thing out of the In-Between. They always come back here in the end, my little horror. Back to the dark between the stars and the world.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 1 (draft)'),
(9101301, 2, 0, 'You eat what you kill and wear what you eat? Messy, messy! Let''s give you something with proper teeth. Hold still... no, the other still!', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 2 (draft)'),
(9101301, 3, 0, 'Ha! Look at you! Now you see it, now you don''t! Blink, blink! I''m calling you Fluffy. No, Snack. No... both!', 12, 0, 100, 4, 0, 0, 0, 0, 'Wren 3 (draft)'),
(9101300, 2, 0, 'A warp stalker. In the villages they tell of a beast that was never quite where you looked, and ate the shadows off the walls. Mind which stories you become.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 2 (draft)'),
(9101301, 4, 0, 'Chores, Fluffy! Every pet in this house has chores. I made a list. It''s a long list. It''s a lovely list!', 12, 0, 100, 25, 0, 0, 0, 0, 'Wren 4 (draft)'),
(9101301, 5, 0, 'Snacks incoming! Catch!', 12, 0, 100, 5, 0, 0, 0, 0, 'Wren 5 (draft)'),
(9101301, 6, 0, 'THAT''S my monster! Again! No, don''t, the ceiling''s loose.', 12, 0, 100, 4, 0, 0, 0, 0, 'Wren 6 (draft)'),
(9101300, 3, 0, 'Listen, then. Before the villages had walls, something crawled out of the In-Between. It had no shape of its own.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 3 (draft)'),
(9101300, 4, 0, 'It ate a wolf and ran on four legs. It ate a man and learned to lie. It ate a king and wore his crown, and no one noticed for a year.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 4 (draft)'),
(9101300, 5, 0, 'When there was nothing left it had not been, it came back here, starving, and began to eat itself.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 5 (draft)'),
(9101300, 6, 0, 'That is what you are, my little horror. Not the wolf, not the man. The hunger underneath. Never let it eat the last of you.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 6 (draft)'),
(9101301, 7, 0, 'Out you go! Come back when you''ve eaten something interesting. Or someone. I''m joking! Mostly. Ha!', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 7 (draft)'),
(9101300, 7, 0, 'The circle lets you go. A circle is worse than a cage, hungry thing: you step out of it yourself, and choose what you become. Come back to us when you need teaching.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 7 (draft)'),
(9101301, 8, 0, 'No dying in my circle! Up you get, Snack. I haven''t finished my list.', 12, 0, 100, 274, 0, 0, 0, 0, 'Wren 8 (PLACEHOLDER)'),
(9101301, 9, 0, 'Ah-ah-ah! The circle holds you until the chores are done.', 12, 0, 100, 274, 0, 0, 0, 0, 'Wren 9 (PLACEHOLDER)'),
(9101301, 10, 0, 'Project #9 is back! Did you bring me anything? No? ...Fine. Lessons, then!', 12, 0, 100, 4, 0, 0, 0, 0, 'Wren 10 (PLACEHOLDER)');

-- --- gossip: the text depends on who asks; training only for a Devourer whose cage is open ---------------
INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `Probability0`) VALUES
(9101300, 'Sit still, hungry thing. The circle is for your sake, not ours.', 'Sit still, hungry thing. The circle is for your sake, not ours.', 1),
(9101301, 'You smell of new meals, my little horror. Sit by the lantern, and I will teach you what the dark already knows about you.', 'You smell of new meals, my little horror. Sit by the lantern, and I will teach you what the dark already knows about you.', 1),
(9101302, 'You are not one of mine. Go back the way the dark let you in, and do not look into the lantern.', 'You are not one of mine. Go back the way the dark let you in, and do not look into the lantern.', 1),
(9101303, 'Chores first, then out of the circle! Or circle first, then chores, then out. I wrote it down somewhere.', 'Chores first, then out of the circle! Or circle first, then chores, then out. I wrote it down somewhere.', 1),
(9101304, 'Project #9! Back already? Lessons! I LOVE lessons. Hold still while I find the list.', 'Project #9! Back already? Lessons! I LOVE lessons. Hold still while I find the list.', 1),
(9101305, 'Ooh, a visitor! You''d make a lovely toad. No? Then shoo! Hagatha says I can''t keep everyone.', 'Ooh, a visitor! You''d make a lovely toad. No? Then shoo! Hagatha says I can''t keep everyone.', 1);
INSERT INTO `gossip_menu` (`MenuID`, `TextID`) VALUES
(9101300, 9101300),
(9101300, 9101301),
(9101300, 9101302),
(9101301, 9101303),
(9101301, 9101304),
(9101301, 9101305);
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES
(9101300, 0, 3, 'I require training.', 0, 5, 16, 0, 0, 0, 0, '', 0, 0),
(9101300, 1, 0, 'I wish to unlearn my talents.', 62295, 16, 16, 4461, 0, 0, 0, '', 0, 0),
(9101300, 2, 0, 'I wish to know about Dual Talent Specialization.', 33762, 20, 1, 10371, 0, 0, 0, '', 0, 0),
(9101300, 3, 0, 'Tell me the tale of the hungry thing.', 0, 1, 1, 0, 0, 0, 0, '', 0, 0),
(9101300, 4, 0, 'Send me back to where you found me.', 0, 1, 1, 0, 0, 0, 0, '', 0, 0),
(9101301, 0, 3, 'I require training.', 0, 5, 16, 0, 0, 0, 0, '', 0, 0),
(9101301, 1, 0, 'I wish to unlearn my talents.', 62295, 16, 16, 4461, 0, 0, 0, '', 0, 0),
(9101301, 2, 0, 'I wish to know about Dual Talent Specialization.', 33762, 20, 1, 10371, 0, 0, 0, '', 0, 0),
(9101301, 4, 0, 'Send me back to where you found me.', 0, 1, 1, 0, 0, 0, 0, '', 0, 0);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14, 9101300, 9101300, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: a caged Devourer'),
(14, 9101300, 9101300, 0, 0, 8, 0, 9101303, 0, 0, 1, 0, 0, '', 'Hagatha: a caged Devourer'),
(14, 9101300, 9101301, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: a freed Devourer'),
(14, 9101300, 9101301, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: a freed Devourer'),
(14, 9101300, 9101302, 0, 0, 15, 0, 512, 0, 0, 1, 0, 0, '', 'Hagatha: anyone else is sent away'),
(15, 9101300, 0, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: I require training. (Devourer)'),
(15, 9101300, 0, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: I require training. (cage open)'),
(15, 9101300, 1, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: I wish to unlearn my talents. (Devourer)'),
(15, 9101300, 1, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: I wish to unlearn my talents. (cage open)'),
(15, 9101300, 2, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: I wish to know about Dual Talent Specialization. (Devourer)'),
(15, 9101300, 2, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: I wish to know about Dual Talent Specialization. (cage open)'),
(15, 9101300, 3, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: Tell me the tale of the hungry thing. (Devourer)'),
(15, 9101300, 3, 0, 0, 9, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: Tell me the tale of the hungry thing. (on the third chore)'),
(15, 9101300, 4, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: Send me back to where you found me. (Devourer)'),
(15, 9101300, 4, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: Send me back to where you found me. (cage open)'),
(14, 9101301, 9101303, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: a caged Devourer'),
(14, 9101301, 9101303, 0, 0, 8, 0, 9101303, 0, 0, 1, 0, 0, '', 'Wren: a caged Devourer'),
(14, 9101301, 9101304, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: a freed Devourer'),
(14, 9101301, 9101304, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: a freed Devourer'),
(14, 9101301, 9101305, 0, 0, 15, 0, 512, 0, 0, 1, 0, 0, '', 'Wren: anyone else is sent away'),
(15, 9101301, 0, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: I require training. (Devourer)'),
(15, 9101301, 0, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: I require training. (cage open)'),
(15, 9101301, 1, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: I wish to unlearn my talents. (Devourer)'),
(15, 9101301, 1, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: I wish to unlearn my talents. (cage open)'),
(15, 9101301, 2, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: I wish to know about Dual Talent Specialization. (Devourer)'),
(15, 9101301, 2, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: I wish to know about Dual Talent Specialization. (cage open)'),
(15, 9101301, 4, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: Send me back to where you found me. (Devourer)'),
(15, 9101301, 4, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: Send me back to where you found me. (cage open)');
