-- Generated by tools/witch_sisters.py (task 010). Do not edit by hand: change the script and run it again.
-- The Hollowmoor sisters (Hagatha Hollowmoor, Wren Hollowmoor): the Devourer's trainers in the In-Between (map 35), their
-- cage and trappings, the three chores of the level-5 intro. Safe to run again; removed by uninstall/world.sql.

-- --- the 16 Devourer Trainers of task 006 are gone (tools/start_kit.py no longer makes them) ------------------
DELETE FROM `creature` WHERE `guid` BETWEEN 9910101 AND 9910116;
DELETE FROM `creature_default_trainer` WHERE `CreatureId` BETWEEN 9101200 AND 9101215;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 9101200 AND 9101215;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 9101200 AND 9101215;
DELETE FROM `gossip_menu_option` WHERE `MenuID` = 9101200;
DELETE FROM `gossip_menu` WHERE `MenuID` = 9101200;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (14, 15) AND `SourceGroup` = 9101200;
DELETE FROM `npc_text` WHERE `ID` IN (9101200, 9101201);

-- --- clean slate for this file's ids ---------------------------------------------------------------------------
DELETE FROM `creature` WHERE `guid` BETWEEN 9910200 AND 9910299;
DELETE FROM `gameobject` WHERE `guid` BETWEEN 9910200 AND 9910299;
DELETE FROM `creature_text` WHERE `CreatureID` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_template_addon` WHERE `entry` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_default_trainer` WHERE `CreatureId` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_queststarter` WHERE `id` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_questender` WHERE `id` BETWEEN 9101300 AND 9101399;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 9101300 AND 9101399;
DELETE FROM `gameobject_template_addon` WHERE `entry` BETWEEN 9101300 AND 9101399;
DELETE FROM `gameobject_template` WHERE `entry` BETWEEN 9101300 AND 9101399;
DELETE FROM `quest_offer_reward` WHERE `ID` BETWEEN 9101301 AND 9101399;
DELETE FROM `quest_request_items` WHERE `ID` BETWEEN 9101301 AND 9101399;
DELETE FROM `quest_template_addon` WHERE `ID` BETWEEN 9101301 AND 9101399;
DELETE FROM `quest_template` WHERE `ID` BETWEEN 9101301 AND 9101399;
DELETE FROM `gossip_menu_option` WHERE `MenuID` IN (9101300, 9101301);
DELETE FROM `gossip_menu` WHERE `MenuID` IN (9101300, 9101301);
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` IN (14, 15) AND `SourceGroup` IN (9101300, 9101301);
DELETE FROM `npc_text` WHERE `ID` BETWEEN 9101300 AND 9101305;

-- --- the sisters ------------------------------------------------------------------------------------------------
-- Copies of a friendly stock NPC (made at install time, so no creature data is written here), as Devourer
-- Trainers, quest givers and gossip; the module's AI (ScriptName) answers the options it owns. Looks: a
-- stock creature's model each (Hagatha: Myranda the Hag 11872; Wren: Windfury Wind Witch 2963, a harpy).
DROP TEMPORARY TABLE IF EXISTS `devourer_tmp_ct`;
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 11872;
UPDATE `devourer_tmp_ct` SET `subname` = 'Devourer Trainer', `minlevel` = 80, `maxlevel` = 80, `faction` = 35,
    `npcflag` = 51, `unit_flags` = 768, `AIName` = '', `ScriptName` = 'npc_devourer_witch_sister', `lootid` = 0, `KillCredit1` = 0,
    `KillCredit2` = 0, `MovementType` = 0, `VerifiedBuild` = 0;
UPDATE `devourer_tmp_ct` SET `entry` = 9101300, `name` = 'Hagatha Hollowmoor', `gossip_menu_id` = 9101300;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101301, `name` = 'Wren Hollowmoor', `gossip_menu_id` = 9101301;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `creature_template` SET `npcflag` = `npcflag` | 128 WHERE `entry` IN (9101300, 9101301);  -- Hagatha buys (owner, 2026-10-03); Wren sells mounts (task 018: their npc_vendor rows belong to the mounts SQL, data/sql/custom/db_world/2026_10_03_10_mounts_adding.sql; this file never touches them)
-- A vendor window only opens with something on sale: plain food and water (the owner may pick other wares).
DELETE FROM `npc_vendor` WHERE `entry` = 9101300;
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(9101300, 0, 159, 0, 0, 0, 0), (9101300, 1, 4540, 0, 0, 0, 0), (9101300, 2, 2678, 0, 0, 0, 0);
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)
SELECT `m`.`entry`, 0, `ctm`.`CreatureDisplayID`, `ctm`.`DisplayScale`, 1, 0 FROM (
    SELECT 9101300 AS `entry`, 11872 AS `looks` UNION ALL SELECT 9101301 AS `entry`, 2963 AS `looks`
) AS `m` JOIN `creature_template_model` AS `ctm` ON `ctm`.`CreatureID` = `m`.`looks` AND `ctm`.`Idx` = 0;
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES
(9101300, 9101200), (9101301, 9101200);

-- --- Wren's snacks (the first chore): rats, hostile, worth no experience; summoned into the cage by the module
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 4075;   -- Rat
UPDATE `devourer_tmp_ct` SET `entry` = 9101302, `name` = 'Wren''s Snack', `subname` = NULL, `minlevel` = 2, `maxlevel` = 3,
    `faction` = 14, `type` = 1, `npcflag` = 0, `unit_flags` = 0, `lootid` = 0, `skinloot` = 0, `pickpocketloot` = 0,
    `mingold` = 0, `maxgold` = 0, `ExperienceModifier` = 0, `DamageModifier` = 0.5, `AIName` = '', `ScriptName` = '',
    `KillCredit1` = 0, `KillCredit2` = 0, `VerifiedBuild` = 0;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)
SELECT 9101302, 0, `CreatureDisplayID`, `DisplayScale`, 1, 0 FROM `creature_template_model` WHERE `CreatureID` = 4075 AND `Idx` = 0;

-- --- Wren's anima pests (the fourth chore): critters, hostile, never fight back, worth no experience;
-- --- summoned around the cages by the module, for each Devourer its own (beetles below, fireflies above)
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 15475;  -- Beetle
UPDATE `devourer_tmp_ct` SET `entry` = 9101313, `name` = 'Anima-Fat Beetle', `subname` = NULL, `minlevel` = 5, `maxlevel` = 5,
    `faction` = 14, `type` = 8, `npcflag` = 0, `unit_flags` = 0, `lootid` = 0, `skinloot` = 0, `pickpocketloot` = 0,
    `mingold` = 0, `maxgold` = 0, `ExperienceModifier` = 0, `DamageModifier` = 0, `AIName` = '', `ScriptName` = 'npc_devourer_anima_pest',
    `KillCredit1` = 0, `KillCredit2` = 0, `MovementType` = 0, `VerifiedBuild` = 0;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101314, `name` = 'Anima-Fat Firefly';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)
SELECT 9101313, 0, `CreatureDisplayID`, `DisplayScale`, 1, 0 FROM `creature_template_model` WHERE `CreatureID` = 15475 AND `Idx` = 0
UNION ALL SELECT 9101314, 0, `CreatureDisplayID`, `DisplayScale`, 1, 0 FROM `creature_template_model` WHERE `CreatureID` = 21076 AND `Idx` = 0;   -- Firefly

-- --- the void under the cage: an unseen, unselectable creature wearing the Void Zone visual ------------------
-- --- and the three quest credits (never spawned; their names are what the quest log would show) ------------
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 15384;  -- OLDWorld Trigger
UPDATE `devourer_tmp_ct` SET `entry` = 9101303, `name` = 'The In-Between', `subname` = NULL, `faction` = 35, `npcflag` = 0,
    `unit_flags` = 33554434, `flags_extra` = 0, `AIName` = '', `ScriptName` = '', `VerifiedBuild` = 0;
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101310, `name` = 'Snack devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101311, `name` = 'Roar at Wren';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101312, `name` = 'Hagatha''s tale heard';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9101315, `name` = 'Anima pest devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`) VALUES
(9101303, 0, 11686, 0.6, 1, 0),
(9101310, 0, 11686, 1, 1, 0),
(9101311, 0, 11686, 1, 1, 0),
(9101312, 0, 11686, 1, 1, 0),
(9101315, 0, 11686, 1, 1, 0);   -- the invisible stalker model
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `visibilityDistanceType`, `auras`) VALUES
(9101303, 0, 0, 0, 0, 0, 0, '64469');

-- --- spawns in the In-Between (map 35) ------------------------------------------------------------------
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `wander_distance`, `MovementType`, `Comment`) VALUES
(9910200, 9101300, 35, 1, 1, -100.4, 153.4, -40.11, 5.3271, 300, 0, 0, 'mod-devourer: Hagatha Hollowmoor'),
(9910201, 9101301, 35, 1, 1, -95.6, 153.4, -40.11, 4.0977, 300, 0, 0, 'mod-devourer: Wren Hollowmoor'),
(9910202, 9101303, 35, 1, 1, -98.0, 150.0, -40.28, 0, 300, 0, 0, 'mod-devourer: the void under the cage');

-- --- game objects: the Devourer's cage (a door: it opens), and the sisters' trappings -------------------------
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `AIName`, `ScriptName`, `VerifiedBuild`) VALUES
(9101300, 0, 4154, 'Wren''s Cage', '', '', '', 1.2, '', '', 0),
(9101301, 5, 1787, 'Wren''s Cage', '', '', '', 1.0, '', '', 0),
(9101302, 5, 216, 'Bubbling Cauldron', '', '', '', 1.0, '', '', 0),
(9101303, 5, 6038, 'Hagatha''s Lantern', '', '', '', 1.0, '', '', 0),
(9101304, 5, 187, 'Bookshelf', '', '', '', 1.0, '', '', 0),
(9101305, 5, 107, 'Book of Monster Tales', '', '', '', 1.0, '', '', 0),
(9101306, 5, 6328, 'Skull Pile', '', '', '', 1.0, '', '', 0),
(9101310, 5, 4152, 'Ritual Candle', '', '', '', 1.0, '', '', 0),
(9101311, 5, 197, 'Ritual Brazier', '', '', '', 1.0, '', '', 0),
(9101312, 5, 7017, 'Ritual Standing Stone', '', '', '', 1.0, '', '', 0),
(9101313, 5, 107, 'Ritual Book', '', '', '', 1.0, '', '', 0);
INSERT INTO `gameobject_template_addon` (`entry`, `faction`, `flags`, `mingold`, `maxgold`) VALUES
(9101300, 0, 16, 0, 0),
(9101301, 0, 0, 0, 0),
(9101302, 0, 0, 0, 0),
(9101303, 0, 0, 0, 0),
(9101304, 0, 0, 0, 0),
(9101305, 0, 0, 0, 0),
(9101306, 0, 0, 0, 0),
(9101310, 0, 0, 0, 0),
(9101311, 0, 0, 0, 0),
(9101312, 0, 0, 0, 0),
(9101313, 0, 0, 0, 0);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `Comment`) VALUES
(9910200, 9101302, 35, 1, 1, -98.0, 157.0, -39.93, 4.7124, 0, 0, 0.707107, -0.707107, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910201, 9101303, 35, 1, 1, -101.9, 155.0, -40.03, 5.3748, 0, 0, 0.43873, -0.898619, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910202, 9101305, 35, 1, 1, -102.7, 152.6, -40.15, 5.7779, 0, 0, 0.249966, -0.968255, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910203, 9101304, 35, 1, 1, -105.5, 160.5, -40.21, 5.3326, 0, 0, 0.457582, -0.889168, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910204, 9101306, 35, 1, 1, -103.5, 157.5, -40.02, 5.3451, 0, 0, 0.452016, -0.89201, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910205, 9101310, 35, 1, 1, -95.23, 151.15, -40.28, 3.5351, 0, 0, 0.980706, -0.195487, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910206, 9101310, 35, 1, 1, -100.77, 151.15, -40.28, 5.8897, 0, 0, 0.195487, -0.980706, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910207, 9101310, 35, 1, 1, -100.77, 148.85, -40.28, 0.3935, 0, 0, 0.195487, 0.980706, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910208, 9101310, 35, 1, 1, -99.15, 147.23, -40.28, 1.1773, 0, 0, 0.555234, 0.831694, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910209, 9101310, 35, 1, 1, -96.85, 147.23, -40.28, 1.9643, 0, 0, 0.831694, 0.555234, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910210, 9101310, 35, 1, 1, -95.23, 148.85, -40.28, 2.7481, 0, 0, 0.980706, 0.195487, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910211, 9101312, 35, 1, 1, -98.0, 154.5, -40.28, 4.7124, 0, 0, 0.707107, -0.707107, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910212, 9101312, 35, 1, 1, -102.5, 150.0, -40.28, 0.0000, 0, 0, 0.0, 1.0, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910213, 9101311, 35, 1, 1, -101.18, 146.82, -40.28, 0.7854, 0, 0, 0.382683, 0.92388, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910214, 9101312, 35, 1, 1, -98.0, 145.5, -40.28, 1.5708, 0, 0, 0.707107, 0.707107, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910215, 9101311, 35, 1, 1, -94.82, 146.82, -40.28, 2.3562, 0, 0, 0.92388, 0.382683, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910216, 9101312, 35, 1, 1, -93.5, 150.0, -40.28, 3.1416, 0, 0, 1.0, 0.0, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910217, 9101313, 35, 1, 1, -99.2, 155.6, -40.1, 4.9235, 0, 0, 0.628678, -0.777666, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910218, 9101313, 35, 1, 1, -96.8, 155.6, -40.1, 4.5013, 0, 0, 0.777666, -0.628678, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910219, 9101301, 35, 1, 1, -92.0, 157.0, -39.93, 4.0038, 0, 0, 0.908513, -0.417857, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910220, 9101301, 35, 1, 1, -108.0, 160.0, -40.12, 5.4978, 0, 0, 0.382683, -0.92388, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910221, 9101301, 35, 1, 1, -88.0, 160.0, -40.11, 3.9270, 0, 0, 0.92388, -0.382683, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910222, 9101301, 35, 1, 1, -108.0, 140.0, -40.31, 0.7854, 0, 0, 0.382683, 0.92388, 300, 0, 1, 'mod-devourer: the In-Between'),
(9910223, 9101301, 35, 1, 1, -88.0, 140.0, -40.24, 2.3562, 0, 0, 0.92388, 0.382683, 300, 0, 1, 'mod-devourer: the In-Between');

-- --- the three chores (class 10 only; each opens after the one before) ------------------------------------
INSERT INTO `quest_template` (`ID`, `QuestType`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestInfoID`, `RewardNextQuest`, `RewardXPDifficulty`, `Flags`, `AllowableRaces`, `LogTitle`, `LogDescription`, `QuestDescription`, `AreaDescription`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGo2`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGoCount2`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `VerifiedBuild`) VALUES
(9101301, 2, 5, 5, 0, 0, 9101302, 4, 0, 0, 'Feeding Time', 'Kill 3 of Wren''s snacks and devour one of them.', 'Fluffy! No, Snack. Project #9! You''ll answer to all of them, I''ve decided.$B$BFirst chore on the list: feeding time! I keep the snacks in the little cages, see? Squeaky ones. I toss them into your circle, you catch them. And don''t just bite them. EAT one. Properly, the way you do. I want to watch!', '', 'Return to Wren Hollowmoor.', 9101302, 9101310, 3, 1, '', 'Snack devoured', '', '', 0),
(9101302, 2, 5, 5, 0, 0, 0, 4, 0, 0, 'A Trick for Wren', 'Roar at Wren Hollowmoor.', 'Every good pet knows a trick. The toad knows ''sit''. The other toad knows ''sit'' too, but louder.$B$BYou, Fluffy, are going to ROAR. Big and scary, right at me. Go on! I''ll pretend to be frightened. I''m very good at it.', '', 'Return to Wren Hollowmoor.', 9101311, 0, 1, 0, 'Roar at Wren', '', '', '', 0),
(9101303, 2, 5, 5, 0, 0, 0, 5, 0, 0, 'What the Dark Remembers', 'Ask Hagatha Hollowmoor for the tale of the hungry thing, and listen to its end.', 'My sister teaches you tricks. I will teach you what you are.$B$BEvery village has a story about something that came out of the dark and ate until it became something else. Sit, hungry thing. Ask me for the tale, and listen to the end of it. The ones who do not listen end up in it.', '', 'Return to Hagatha Hollowmoor.', 9101312, 0, 1, 0, 'Hear Hagatha''s tale', '', '', '', 0),
(9101304, 2, 5, 5, 0, 0, 0, 5, 0, 0, 'Pests in the Cells', 'Devour every anima-fat pest around Wren''s cages. Some of them can only be reached with your tongue.', 'Snack, I have a teeny problem. The bugs I test my spells on? They got out. All of them. They crawled off around the cells and found Hagatha''s store of anima, and they''ve been feasting on it, and now they MULTIPLY. Every time I catch one and squash it, there are more! I can''t cage the anima that comes flowing out of them.$B$BBut an ancient horror like you is made for exactly this. Just eat them. They might not be tasty... hmm, maybe you''ll learn to like them. Here, I''ll help you with it. Hold still!', '', 'Return to Wren Hollowmoor.', 9101315, 0, 10, 0, 'Anima pest devoured', '', '', '', 0),
(9101305, 2, 5, 5, 0, 0, 0, 3, 0, 0, 'Wren''s Apprentice', 'Let Wren introduce her apprentice, and take her with you into the world.', 'Snack, meet Bramble! She''s my apprentice. Well, SHE says she''s my apprentice. I say she''s a gnome who followed a cat into the In-Between and never found the way out again.$B$BShe wants to see the world, and you need somebody to tell you which mushrooms not to eat. Take her with you! Bring her back with all her fingers.', '', 'Return to Wren Hollowmoor.', 0, 0, 0, 0, '', '', '', '', 0);
INSERT INTO `quest_template_addon` (`ID`, `AllowableClasses`, `PrevQuestID`) VALUES
(9101301, 512, 0),
(9101302, 512, 9101301),
(9101303, 512, 9101302),
(9101304, 512, 9101303),
(9101305, 512, 9101303);
INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`, `VerifiedBuild`) VALUES
(9101301, 1, 1, 'Still squeaking in there? Somebody''s not done.', 0),
(9101302, 1, 1, 'I''m waiting! Rooooar. Like that, but you.', 0),
(9101303, 1, 1, 'The tale is not finished with you yet.', 0),
(9101304, 1, 1, 'I can still hear crunching, and it isn''t you. Keep eating!', 0),
(9101305, 1, 1, 'Well? She''s right there, pretending to be a coat stand.', 0);
INSERT INTO `quest_offer_reward` (`ID`, `Emote1`, `RewardText`, `VerifiedBuild`) VALUES
(9101301, 1, 'Crunchy! Hagatha, did you see? It ate it whole! Well. Mostly whole.$B$BGold star, Snack. Next chore!', 0),
(9101302, 1, 'Eek! Ha! Oh, that was GOOD. That goes on the list of things you''re good at. It''s a short list. It''s a new list!$B$BNow go and sit nicely for Hagatha. She''s been dying to frighten you back.', 0),
(9101303, 1, 'Now you know the shape beneath all your shapes. Remember it when you wear someone else''s.$B$BWren, break the circle. Our little horror has lessons to carry into the world, and it will come back to us for more.', 0),
(9101304, 1, 'All of them? ALL of them? Oh, you lovely, horrible thing. Hagatha''s anima is safe and nothing is multiplying any more.$B$BKeep the frog. It suits you.', 0),
(9101305, 1, 'There! Now you''re a pack. A very small, very odd pack.$B$BBramble, don''t let Snack eat you. Snack, don''t let her set you on fire. Again.', 0);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES
(9101301, 9101301), (9101301, 9101302), (9101300, 9101303), (9101301, 9101304), (9101301, 9101305);
INSERT INTO `creature_questender` (`id`, `quest`) VALUES
(9101301, 9101301), (9101301, 9101302), (9101300, 9101303), (9101301, 9101304), (9101301, 9101305);

-- --- the molt quests (task 018): the module hands one out when a form is ready to evolve; Wren takes it ---
INSERT INTO `quest_template` (`ID`, `QuestType`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestInfoID`, `RewardNextQuest`, `RewardXPDifficulty`, `Flags`, `AllowableRaces`, `LogTitle`, `LogDescription`, `QuestDescription`, `AreaDescription`, `QuestCompletionLog`, `VerifiedBuild`) VALUES
(9101310, 2, 12, 12, 0, 0, 0, 5, 0, 0, 'The Molt: Greater Plainstrider', 'Go back to Wren Hollowmoor in the In-Between and let her peel your plainstrider body. A greater plainstrider is waiting under the old skin.', 'Your plainstrider body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101311, 2, 14, 14, 0, 0, 0, 5, 0, 0, 'The Molt: Bloodsnout Worg', 'Go back to Wren Hollowmoor in the In-Between and let her peel your wolf body. A bloodsnout worg is waiting under the old skin.', 'Your wolf body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101312, 2, 12, 12, 0, 0, 0, 5, 0, 0, 'The Molt: Raging Agam''ar', 'Go back to Wren Hollowmoor in the In-Between and let her peel your boar body. A raging agam''ar is waiting under the old skin.', 'Your boar body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101313, 2, 14, 14, 0, 0, 0, 5, 0, 0, 'The Molt: Shadowclaw', 'Go back to Wren Hollowmoor in the In-Between and let her peel your saber body. A shadowclaw is waiting under the old skin.', 'Your saber body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101314, 2, 12, 12, 0, 0, 0, 5, 0, 0, 'The Molt: Rockjaw Backbreaker', 'Go back to Wren Hollowmoor in the In-Between and let her peel your trogg body. A rockjaw backbreaker is waiting under the old skin.', 'Your trogg body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101315, 2, 14, 14, 0, 0, 0, 5, 0, 0, 'The Molt: Vampiric Duskbat', 'Go back to Wren Hollowmoor in the In-Between and let her peel your bat body. A vampiric duskbat is waiting under the old skin.', 'Your bat body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101316, 2, 14, 14, 0, 0, 0, 5, 0, 0, 'The Molt: Arcane Wraith', 'Go back to Wren Hollowmoor in the In-Between and let her peel your mana wyrm body. A arcane wraith is waiting under the old skin.', 'Your mana wyrm body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101317, 2, 12, 12, 0, 0, 0, 5, 0, 0, 'The Molt: Royal Blue Flutterer', 'Go back to Wren Hollowmoor in the In-Between and let her peel your moth body. A royal blue flutterer is waiting under the old skin.', 'Your moth body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101318, 2, 16, 16, 0, 0, 0, 5, 0, 0, 'The Molt: Void Terror', 'Go back to Wren Hollowmoor in the In-Between and let her peel your warp stalker body. A void terror is waiting under the old skin.', 'Your warp stalker body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101319, 2, 28, 28, 0, 0, 0, 5, 0, 0, 'The Molt: Baby Wind Serpent', 'Go back to Wren Hollowmoor in the In-Between and let her peel your viper body. A baby wind serpent is waiting under the old skin.', 'Your viper body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101320, 2, 30, 30, 0, 0, 0, 5, 0, 0, 'The Molt: Komodo Dragon', 'Go back to Wren Hollowmoor in the In-Between and let her peel your baby komodo body. A komodo dragon is waiting under the old skin.', 'Your baby komodo body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101321, 2, 35, 35, 0, 0, 0, 5, 0, 0, 'The Molt: Spikeshell', 'Go back to Wren Hollowmoor in the In-Between and let her peel your snapjaw body. A spikeshell is waiting under the old skin.', 'Your snapjaw body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101322, 2, 14, 14, 0, 0, 0, 5, 0, 0, 'The Molt: Water Salamander', 'Go back to Wren Hollowmoor in the In-Between and let her peel your biletoad body. A water salamander is waiting under the old skin.', 'Your biletoad body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0),
(9101323, 2, 44, 44, 0, 0, 0, 5, 0, 0, 'The Molt: Sethrak', 'Go back to Wren Hollowmoor in the In-Between and let her peel your baby wind serpent body. A sethrak is waiting under the old skin.', 'Your baby wind serpent body has eaten enough. It itches, it pulls, it does not fit any more. The sisters can feel it from the In-Between.', '', 'Return to Wren Hollowmoor.', 0);
INSERT INTO `quest_template_addon` (`ID`, `AllowableClasses`, `PrevQuestID`) VALUES
(9101310, 512, 9101303),
(9101311, 512, 9101303),
(9101312, 512, 9101303),
(9101313, 512, 9101303),
(9101314, 512, 9101303),
(9101315, 512, 9101303),
(9101316, 512, 9101303),
(9101317, 512, 9101303),
(9101318, 512, 9101303),
(9101319, 512, 9101303),
(9101320, 512, 9101303),
(9101321, 512, 9101303),
(9101322, 512, 9101303),
(9101323, 512, 9101303);
INSERT INTO `quest_offer_reward` (`ID`, `Emote1`, `RewardText`, `VerifiedBuild`) VALUES
(9101310, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101311, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101312, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101313, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101314, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101315, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101316, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101317, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101318, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101319, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101320, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101321, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101322, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0),
(9101323, 1, 'There you are! Look how it bulges. Lie down in the circle, Snack, and don''t wriggle. Hagatha, the bucket!', 0);
INSERT INTO `creature_questender` (`id`, `quest`) VALUES
(9101301, 9101310), (9101301, 9101311), (9101301, 9101312), (9101301, 9101313), (9101301, 9101314), (9101301, 9101315), (9101301, 9101316), (9101301, 9101317), (9101301, 9101318), (9101301, 9101319), (9101301, 9101320), (9101301, 9101321), (9101301, 9101322), (9101301, 9101323);

-- --- what they say (creature_text; the module calls the groups at the right moments) ---------------------
INSERT INTO `creature_text` (`CreatureID`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(9101301, 0, 0, 'Found you! Hold still, Snack. This tickles. Mostly.', 15, 0, 100, 0, 0, 0, 0, 0, 'Wren 0 (draft)'),
(9101300, 0, 0, 'Hush, sister. Let it wake slowly. The ones that wake fast bite the hand that feeds them.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 0 (draft)'),
(9101301, 1, 0, 'It''s awake! Hagatha, it''s AWAKE! Hello, hello, Project #9! Don''t smudge the circle, the chalk is new.', 12, 0, 100, 5, 0, 0, 0, 0, 'Wren 1 (draft)'),
(9101300, 1, 0, 'So. Another hungry thing out of the In-Between. They always come back here in the end, my little horror. Back to the dark between the stars and the world.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 1 (draft)'),
(9101301, 2, 0, 'You eat what you kill and wear what you eat? Messy, messy! Let''s give you something with proper teeth. Hold still... no, the other still!', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 2 (draft)'),
(9101301, 3, 0, 'Ha! Look at you! Now you see it, now you don''t! Blink, blink! I''m calling you Fluffy. No, Snack. No... both!', 12, 0, 100, 4, 0, 0, 0, 0, 'Wren 3 (draft)'),
(9101300, 2, 0, 'A warp stalker. In the villages they tell of a beast that was never quite where you looked, and ate the shadows off the walls. Mind which stories you become.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 2 (draft)'),
(9101301, 4, 0, 'Chores, Fluffy! Every pet in this house has chores. I made a list. It''s a long list. It''s a lovely list!', 12, 0, 100, 25, 0, 0, 0, 0, 'Wren 4 (draft)'),
(9101301, 5, 0, 'Snacks incoming! Catch!', 12, 0, 100, 5, 0, 0, 0, 0, 'Wren 5 (draft)'),
(9101301, 6, 0, 'THAT''S my monster! Again! No, don''t, the ceiling''s loose.', 12, 0, 100, 4, 0, 0, 0, 0, 'Wren 6 (draft)'),
(9101300, 3, 0, 'Listen, then. Before the villages had walls, something crawled out of the In-Between. It had no shape of its own.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 3 (draft)'),
(9101300, 4, 0, 'It ate a wolf and ran on four legs. It ate a man and learned to lie. It ate a king and wore his crown, and no one noticed for a year.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 4 (draft)'),
(9101300, 5, 0, 'When there was nothing left it had not been, it came back here, starving, and began to eat itself.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 5 (draft)'),
(9101300, 6, 0, 'That is what you are, my little horror. Not the wolf, not the man. The hunger underneath. Never let it eat the last of you.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 6 (draft)'),
(9101301, 7, 0, 'Out you go! Come back when you''ve eaten something interesting. Or someone. I''m joking! Mostly. Ha!', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 7 (draft)'),
(9101300, 7, 0, 'The circle lets you go. A circle is worse than a cage, hungry thing: you step out of it yourself, and choose what you become. Come back to us when you need teaching.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 7 (draft)'),
(9101301, 8, 0, 'No dying in my circle! Up you get, Snack. I haven''t finished my list.', 12, 0, 100, 274, 0, 0, 0, 0, 'Wren 8 (PLACEHOLDER)'),
(9101301, 9, 0, 'Ah-ah-ah! The circle holds you until the chores are done.', 12, 0, 100, 274, 0, 0, 0, 0, 'Wren 9 (PLACEHOLDER)'),
(9101301, 10, 0, 'Project #9 is back! Did you bring me anything? No? ...Fine. Lessons, then!', 12, 0, 100, 4, 0, 0, 0, 0, 'Wren 10 (PLACEHOLDER)'),
(9101301, 11, 0, 'Hold still, Snack! A little swamp, a little croak... there!', 12, 0, 100, 5, 0, 0, 0, 0, 'Wren 11 (draft)'),
(9101301, 12, 0, 'Ha! A toad! The best kind of pet. Now go and eat my bugs. And look up: some of them hide where only a tongue can reach!', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 12 (draft)'),
(9101301, 13, 0, 'Was that the last one? I think that was the last one! Come here and let me count.', 12, 0, 100, 4, 0, 0, 0, 0, 'Wren 13 (draft)'),
(9101301, 14, 0, 'Ooh, here it comes! Hold still, Snack, the old skin''s coming off! ...Eww. Wonderful!', 12, 0, 100, 4, 0, 0, 0, 0, 'Wren 14 (draft)'),
(9101301, 15, 0, 'Snack! I can smell it from here: that body of yours is fit to burst. Come home and let me peel it!', 12, 0, 100, 0, 0, 0, 0, 0, 'Wren 15 (draft)'),
(9101300, 8, 0, 'In Mulgore they tell of a chick that never stopped running. The wind caught up with it once, and has been chasing it ever since.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 8 (draft)'),
(9101300, 9, 0, 'Every pack has one that runs behind the others. Not out of fear, my little horror. It is choosing which leg to take first.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 9 (draft)'),
(9101300, 10, 0, 'The quilboar have a word for a boar that has been struck so often it forgot how to fall. They pray to it.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 10 (draft)'),
(9101300, 11, 0, 'On Darkshore they say a black cat once swallowed a scream, and it has hunted in silence ever since. Mind your voice near it.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 11 (draft)'),
(9101300, 12, 0, 'The dwarves tell of a trogg that gnawed on a stone giant''s toe. It never stopped growing harder. Neither did its hunger.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 12 (draft)'),
(9101300, 13, 0, 'In Tirisfal the bats grew fat on what the plague left behind. Then the plague left nothing, and they came for the living.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 13 (draft)'),
(9101300, 14, 0, 'When the elves spill their magic, something always laps it up. That something does not stop when the cup is empty.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 14 (draft)'),
(9101300, 15, 0, 'The draenei say the bluest moths dream for the ones they put to sleep. Never ask them what they dream about.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 15 (draft)'),
(9101300, 16, 0, 'Out where the world thins, the warp stalkers grow until they forget which side of the dark they belong to.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 16 (draft)'),
(9101300, 17, 0, 'A snake that swallows enough storms grows wings to carry them. The tauren say the thunder is only the wind serpents clearing their throats.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 17 (draft)'),
(9101300, 18, 0, 'On the islands of the south they say a bite from the great lizards never heals. They are wrong, my little horror. It heals inside the lizard.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 18 (draft)'),
(9101300, 19, 0, 'Old turtles grow spikes because the world kept biting them. You will understand that, little horror.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 19 (draft)'),
(9101300, 20, 0, 'Toads stay in the swamp. The salamander is the one that crawled into the hot springs and liked it. Do not let it near my cauldron.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 20 (draft)'),
(9101300, 21, 0, 'Every serpent that sheds long enough stands up one day and starts to pray. The sand people began like you, my little horror: as something that would not stop eating.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 21 (draft)'),
(9101300, 22, 0, 'The sand people of the far south shed their skins to grow wiser. You shed theirs to grow hungrier. They would not approve.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 22 (draft)'),
(9101300, 23, 0, 'Some hungers come back from the In-Between with teeth of their own. The berserker is what happens when nothing ever tells them no.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 23 (draft)'),
(9101300, 24, 0, 'A serpent that learned to pray, and a prayer that learned to bite. Its echoes rise from the ground because the ground remembers it.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 24 (draft)'),
(9101300, 25, 0, 'Every terror was small once. This one still squeaks when it is hungry. Enjoy that while it lasts.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 25 (draft)'),
(9101300, 26, 0, 'In Elwynn they tell of a wolf that followed a shepherd for a whole year and never touched a sheep. It was waiting for the shepherd.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 26 (draft)'),
(9101300, 27, 0, 'The troggs came up out of the stone hungry, and they have not been full since. You will understand them better than the dwarves ever did.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 27 (draft)'),
(9101300, 28, 0, 'The night elves say their sabers walk between the moonbeams. They never say what the sabers eat there.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 28 (draft)'),
(9101300, 29, 0, 'Moths fly to the light because they remember the In-Between: the only bright thing they ever saw there was the way out.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 29 (draft)'),
(9101300, 30, 0, 'The orcs say a boar charges because it never learned how to stop. Neither have you, my little horror.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 30 (draft)'),
(9101300, 31, 0, 'The tauren children race the striders across the plains, and the striders let them win. Mostly.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 31 (draft)'),
(9101300, 32, 0, 'In Tirisfal the bats listen at the windows of the dead. They learn the name of everyone who is buried, and they never forget a meal.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 32 (draft)'),
(9101300, 33, 0, 'The elves made a well of magic, and the wyrms came to drink from it. Then the well was gone, and the wyrms were still thirsty.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 33 (draft)'),
(9101300, 34, 0, 'A toad in a cell eats the bugs, the bugs eat the crumbs, and the crumbs were the last prisoner. Everything in here eats something.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 34 (draft)'),
(9101300, 35, 0, 'The swamp folk say a frog that eats enough flies will one day swallow the swamp. You are halfway there.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 35 (draft)'),
(9101300, 36, 0, 'The snakes of the Wailing Caverns drank the sickness of a dreaming druid and grew clever. Clever things in the dark are the worst kind.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 36 (draft)'),
(9101300, 37, 0, 'The trolls of Zul''Aman raised their eagles on the hearts of their enemies. This one has not yet decided whose heart it wants.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 37 (draft)'),
(9101300, 38, 0, 'The sailors say a snapjaw once bit the anchor off a ship and slept with it for a hundred years. Turtles are very good at keeping what they bite.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 38 (draft)'),
(9101300, 39, 0, 'Small lizards learn patience in the mud. They wait, they bite once, and then they simply follow until the bite does the rest.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 39 (draft)'),
(9101300, 40, 0, 'That shape has no story yet. Eat a little more of the world, and the world will write you one.', 12, 0, 100, 1, 0, 0, 0, 0, 'Hagatha 40 (draft)'),
(9101301, 16, 0, 'Fluffy! Actually fluffy this time! Can I brush you? No? I''m brushing you.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 16 (draft)'),
(9101301, 17, 0, 'Look at those legs! You could outrun Hagatha''s temper. Almost.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 17 (draft)'),
(9101301, 18, 0, 'Ooh, wings! Don''t fly near the candles, Snack. We''ve talked about the candles.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 18 (draft)'),
(9101301, 19, 0, 'Upside down, please, that''s how I like my bats. No? Fine. Rightside up.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 19 (draft)'),
(9101301, 20, 0, 'My toad! Hello, my toad! Did you eat any bugs? Of course you did.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 20 (draft)'),
(9101301, 21, 0, 'You''re all sparkly and wrong-looking. I love it. Don''t touch the cauldron.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 21 (draft)'),
(9101301, 22, 0, 'Ew. EW! You smell like a cave. A good cave! But a cave.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 22 (draft)'),
(9101301, 23, 0, 'A shell! Can I live in it? No? Can I knock? Hello in there!', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 23 (draft)'),
(9101301, 24, 0, 'Sssso fancy! Sorry. I had to.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 24 (draft)'),
(9101301, 25, 0, 'A lizard! Do you want a warm rock? I keep a warm rock for lizards. Don''t bite it.', 12, 0, 100, 11, 0, 0, 0, 0, 'Wren 25 (draft)'),
(9101301, 26, 0, 'Bramble! Out from behind the cauldron, you''re going with Snack! Take your good boots. And the bucket. No, not that bucket.', 12, 0, 100, 5, 0, 0, 0, 0, 'Wren 26 (draft)');

-- --- gossip: the text depends on who asks; training only for a Devourer whose cage is open ---------------
INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `Probability0`) VALUES
(9101300, 'Sit still, hungry thing. The circle is for your sake, not ours.', 'Sit still, hungry thing. The circle is for your sake, not ours.', 1),
(9101301, 'You smell of new meals, my little horror. Sit by the lantern, and I will teach you what the dark already knows about you.', 'You smell of new meals, my little horror. Sit by the lantern, and I will teach you what the dark already knows about you.', 1),
(9101302, 'You are not one of mine. Go back the way the dark let you in, and do not look into the lantern.', 'You are not one of mine. Go back the way the dark let you in, and do not look into the lantern.', 1),
(9101303, 'Chores first, then out of the circle! Or circle first, then chores, then out. I wrote it down somewhere.', 'Chores first, then out of the circle! Or circle first, then chores, then out. I wrote it down somewhere.', 1),
(9101304, 'Project #9! Back already? Lessons! I LOVE lessons. Hold still while I find the list.', 'Project #9! Back already? Lessons! I LOVE lessons. Hold still while I find the list.', 1),
(9101305, 'Ooh, a visitor! You''d make a lovely toad. No? Then shoo! Hagatha says I can''t keep everyone.', 'Ooh, a visitor! You''d make a lovely toad. No? Then shoo! Hagatha says I can''t keep everyone.', 1);
INSERT INTO `gossip_menu` (`MenuID`, `TextID`) VALUES
(9101300, 9101300),
(9101300, 9101301),
(9101300, 9101302),
(9101301, 9101303),
(9101301, 9101304),
(9101301, 9101305);
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`, `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`, `VerifiedBuild`) VALUES
(9101300, 0, 3, 'I require training.', 0, 5, 16, 0, 0, 0, 0, '', 0, 0),
(9101300, 1, 0, 'I wish to unlearn my talents.', 62295, 16, 16, 4461, 0, 0, 0, '', 0, 0),
(9101300, 2, 0, 'I wish to know about Dual Talent Specialization.', 33762, 20, 1, 10371, 0, 0, 0, '', 0, 0),
(9101300, 5, 1, 'I have things to sell.', 0, 3, 128, 0, 0, 0, 0, '', 0, 0),
(9101300, 3, 0, 'Tell me the tale of the hungry thing.', 0, 1, 1, 0, 0, 0, 0, '', 0, 0),
(9101300, 6, 0, 'Tell me about the shape I wear.', 0, 1, 1, 0, 0, 0, 0, '', 0, 0),
(9101300, 4, 0, 'Send me back to where you found me.', 0, 1, 1, 0, 0, 0, 0, '', 0, 0),
(9101301, 0, 3, 'I require training.', 0, 5, 16, 0, 0, 0, 0, '', 0, 0),
(9101301, 1, 0, 'I wish to unlearn my talents.', 62295, 16, 16, 4461, 0, 0, 0, '', 0, 0),
(9101301, 2, 0, 'I wish to know about Dual Talent Specialization.', 33762, 20, 1, 10371, 0, 0, 0, '', 0, 0),
(9101301, 4, 0, 'Send me back to where you found me.', 0, 1, 1, 0, 0, 0, 0, '', 0, 0),
(9101301, 7, 1, 'Show me the mounts you made.', 0, 3, 128, 0, 0, 0, 0, '', 0, 0);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(14, 9101300, 9101300, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: a caged Devourer'),
(14, 9101300, 9101300, 0, 0, 8, 0, 9101303, 0, 0, 1, 0, 0, '', 'Hagatha: a caged Devourer'),
(14, 9101300, 9101301, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: a freed Devourer'),
(14, 9101300, 9101301, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: a freed Devourer'),
(14, 9101300, 9101302, 0, 0, 15, 0, 512, 0, 0, 1, 0, 0, '', 'Hagatha: anyone else is sent away'),
(15, 9101300, 0, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: I require training. (Devourer)'),
(15, 9101300, 0, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: I require training. (cage open)'),
(15, 9101300, 1, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: I wish to unlearn my talents. (Devourer)'),
(15, 9101300, 1, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: I wish to unlearn my talents. (cage open)'),
(15, 9101300, 2, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: I wish to know about Dual Talent Specialization. (Devourer)'),
(15, 9101300, 2, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: I wish to know about Dual Talent Specialization. (cage open)'),
(15, 9101300, 5, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: I have things to sell. (Devourer)'),
(15, 9101300, 5, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: I have things to sell. (cage open)'),
(15, 9101300, 3, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: Tell me the tale of the hungry thing. (Devourer)'),
(15, 9101300, 3, 0, 0, 9, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: Tell me the tale of the hungry thing. (on the third chore)'),
(15, 9101300, 6, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: Tell me about the shape I wear. (Devourer)'),
(15, 9101300, 6, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: Tell me about the shape I wear. (cage open)'),
(15, 9101300, 4, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Hagatha: Send me back to where you found me. (Devourer)'),
(15, 9101300, 4, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Hagatha: Send me back to where you found me. (cage open)'),
(14, 9101301, 9101303, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: a caged Devourer'),
(14, 9101301, 9101303, 0, 0, 8, 0, 9101303, 0, 0, 1, 0, 0, '', 'Wren: a caged Devourer'),
(14, 9101301, 9101304, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: a freed Devourer'),
(14, 9101301, 9101304, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: a freed Devourer'),
(14, 9101301, 9101305, 0, 0, 15, 0, 512, 0, 0, 1, 0, 0, '', 'Wren: anyone else is sent away'),
(15, 9101301, 0, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: I require training. (Devourer)'),
(15, 9101301, 0, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: I require training. (cage open)'),
(15, 9101301, 1, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: I wish to unlearn my talents. (Devourer)'),
(15, 9101301, 1, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: I wish to unlearn my talents. (cage open)'),
(15, 9101301, 2, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: I wish to know about Dual Talent Specialization. (Devourer)'),
(15, 9101301, 2, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: I wish to know about Dual Talent Specialization. (cage open)'),
(15, 9101301, 4, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: Send me back to where you found me. (Devourer)'),
(15, 9101301, 4, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: Send me back to where you found me. (cage open)'),
(15, 9101301, 7, 0, 0, 15, 0, 512, 0, 0, 0, 0, 0, '', 'Wren: Show me the mounts you made. (Devourer)'),
(15, 9101301, 7, 0, 0, 8, 0, 9101303, 0, 0, 0, 0, 0, '', 'Wren: Show me the mounts you made. (cage open)');
