-- mod-devourer task 021: the Devourer's quests in the world (Hagatha's lanterns). src/DevourerQuests.cpp.
-- Generated by tools/devourer_quests.py -- change the tool and run it again. Safe to run again.
-- Ids 9105000-9105999 (quests, credits, lanterns, objects), gameobject guids 9920000-9920999.

DELETE FROM `gameobject` WHERE `guid` BETWEEN 9920000 AND 9920999;
DELETE FROM `gameobject_queststarter` WHERE `quest` BETWEEN 9105000 AND 9105399;
DELETE FROM `gameobject_questender` WHERE `quest` BETWEEN 9105000 AND 9105399;
DELETE FROM `creature_queststarter` WHERE `quest` BETWEEN 9105000 AND 9105399;
DELETE FROM `creature_questender` WHERE `quest` BETWEEN 9105000 AND 9105399;
DELETE FROM `gameobject_template` WHERE `entry` BETWEEN 9105000 AND 9105199;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 9105400 AND 9105999;
DELETE FROM `creature_template` WHERE `entry` BETWEEN 9105400 AND 9105999;
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId` = 19 AND `SourceEntry` BETWEEN 9105000 AND 9105399;
DELETE FROM `quest_offer_reward` WHERE `ID` BETWEEN 9105000 AND 9105399;
DELETE FROM `quest_request_items` WHERE `ID` BETWEEN 9105000 AND 9105399;
DELETE FROM `quest_template_addon` WHERE `ID` BETWEEN 9105000 AND 9105399;
DELETE FROM `quest_template` WHERE `ID` BETWEEN 9105000 AND 9105399;

-- --- Hagatha's lanterns (questgivers, one per region) and the witches' objects (goobers, one quest each) ---
INSERT INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `IconName`, `castBarCaption`, `unk1`, `size`, `Data0`, `Data1`, `AIName`, `ScriptName`, `VerifiedBuild`) VALUES
(9105000, 2, 6038, 'Hagatha''s Lantern', '', '', '', 1.4, 0, 0, '', '', 0),
(9105001, 2, 6038, 'Hagatha''s Lantern', '', '', '', 1.4, 0, 0, '', '', 0),
(9105002, 2, 6038, 'Hagatha''s Lantern', '', '', '', 1.4, 0, 0, '', '', 0),
(9105003, 2, 6038, 'Hagatha''s Lantern', '', '', '', 1.4, 0, 0, '', '', 0),
(9105004, 2, 6038, 'Hagatha''s Lantern', '', '', '', 1.4, 0, 0, '', '', 0),
(9105005, 2, 6038, 'Hagatha''s Lantern', '', '', '', 1.4, 0, 0, '', '', 0),
(9105006, 2, 6038, 'Hagatha''s Lantern', '', '', '', 1.4, 0, 0, '', '', 0),
(9105007, 2, 6038, 'Hagatha''s Lantern', '', '', '', 1.4, 0, 0, '', '', 0),
(9105100, 10, 216, 'Hagatha''s Bait', '', '', '', 0.7, 0, 9105062, '', 'go_devourer_quest_object', 0);

INSERT INTO `gameobject` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `Comment`) VALUES
(9920000, 9105000, 0, 1, 1, -9620.0, -560.0, 54.44, 2.4, 0, 0, 0.932039, 0.362358, 300, 255, 1, 'mod-devourer: Hagatha''s Lantern, south-east of Crystal Lake'),
(9920001, 9105001, 0, 1, 1, -5620.0, -1100.0, 392.25, 1.2, 0, 0, 0.564642, 0.825336, 300, 255, 1, 'mod-devourer: Hagatha''s Lantern, the hills east of Kharanos'),
(9920002, 9105002, 1, 1, 1, 9810.0, 840.0, 1304.01, 3.9, 0, 0, 0.92896, -0.370181, 300, 255, 1, 'mod-devourer: Hagatha''s Lantern, the woods south-east of Dolanaar'),
(9920003, 9105003, 530, 1, 1, -4050.0, -12000.0, 1.55, 5.1, 0, 0, 0.557684, -0.830054, 300, 255, 1, 'mod-devourer: Hagatha''s Lantern, Moongraze Woods'),
(9920004, 9105004, 1, 1, 1, 300.0, -4500.0, 28.58, 0.7, 0, 0, 0.342898, 0.939373, 300, 255, 1, 'mod-devourer: Hagatha''s Lantern, the scrub west of Razor Hill'),
(9920005, 9105005, 1, 1, 1, -2100.0, -900.0, -1.06, 2.0, 0, 0, 0.841471, 0.540302, 300, 255, 1, 'mod-devourer: Hagatha''s Lantern, the plains north-east of Bloodhoof'),
(9920006, 9105006, 0, 1, 1, 2500.0, 600.0, 30.68, 4.4, 0, 0, 0.808496, -0.588501, 300, 255, 1, 'mod-devourer: Hagatha''s Lantern, the glades north-west of Brill'),
(9920007, 9105007, 530, 1, 1, 8900.0, -6600.0, 33.61, 1.6, 0, 0, 0.717356, 0.696707, 300, 255, 1, 'mod-devourer: Hagatha''s Lantern, the woods west of the Dead Scar'),
(9920008, 9105100, 1, 1, 1, -1740.0, -545.0, -10.9, 0.0, 0, 0, 0.0, 1.0, 60, 255, 1, 'mod-devourer: Hagatha''s Bait');

-- --- credits: one per objective the core cannot count by itself (never spawned) -----------------------
DROP TEMPORARY TABLE IF EXISTS `devourer_tmp_ct`;
CREATE TEMPORARY TABLE `devourer_tmp_ct` SELECT * FROM `creature_template` WHERE `entry` = 15384;
UPDATE `devourer_tmp_ct` SET `subname` = NULL, `faction` = 35, `npcflag` = 0, `unit_flags` = 33554434, `flags_extra` = 0, `AIName` = '', `ScriptName` = '', `VerifiedBuild` = 0;
UPDATE `devourer_tmp_ct` SET `entry` = 9105400, `name` = 'Elwynn wolf devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105401, `name` = 'Rockhide Boar devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105402, `name` = 'Young Forest Bear devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105403, `name` = 'Forest or Mine Spider devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105404, `name` = 'Hogger devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105405, `name` = 'Snow Leopard devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105406, `name` = 'Ice Claw Bear devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105407, `name` = 'Winter Wolf devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105408, `name` = 'Rockjaw trogg devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105409, `name` = 'Rockjaw Backbreaker devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105410, `name` = 'Nightsaber devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105411, `name` = 'Strigid owl devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105412, `name` = 'Lady Sathrah devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105413, `name` = 'Timberstrider devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105414, `name` = 'Root Trapper devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105415, `name` = 'Moongraze deer devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105416, `name` = 'Moonwing owlbeast devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105417, `name` = 'Mottled boar devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105418, `name` = 'Bloodtalon raptor devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105419, `name` = 'Durotar scorpid devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105420, `name` = 'Dreadmaw Crocolisk devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105421, `name` = 'Plainstrider devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105422, `name` = 'Prairie wolf devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105423, `name` = 'Flatland cougar devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105424, `name` = 'Mazzranache devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105425, `name` = 'Duskbat devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105426, `name` = 'Darkhound devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105427, `name` = 'Scarlet crusader devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105428, `name` = 'Spilled magic devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105429, `name` = 'Crazed Dragonhawk devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
UPDATE `devourer_tmp_ct` SET `entry` = 9105430, `name` = 'Wretched devoured';
INSERT INTO `creature_template` SELECT * FROM `devourer_tmp_ct`;
DROP TEMPORARY TABLE `devourer_tmp_ct`;
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`) VALUES
(9105400, 0, 11686, 1, 1, 0),
(9105401, 0, 11686, 1, 1, 0),
(9105402, 0, 11686, 1, 1, 0),
(9105403, 0, 11686, 1, 1, 0),
(9105404, 0, 11686, 1, 1, 0),
(9105405, 0, 11686, 1, 1, 0),
(9105406, 0, 11686, 1, 1, 0),
(9105407, 0, 11686, 1, 1, 0),
(9105408, 0, 11686, 1, 1, 0),
(9105409, 0, 11686, 1, 1, 0),
(9105410, 0, 11686, 1, 1, 0),
(9105411, 0, 11686, 1, 1, 0),
(9105412, 0, 11686, 1, 1, 0),
(9105413, 0, 11686, 1, 1, 0),
(9105414, 0, 11686, 1, 1, 0),
(9105415, 0, 11686, 1, 1, 0),
(9105416, 0, 11686, 1, 1, 0),
(9105417, 0, 11686, 1, 1, 0),
(9105418, 0, 11686, 1, 1, 0),
(9105419, 0, 11686, 1, 1, 0),
(9105420, 0, 11686, 1, 1, 0),
(9105421, 0, 11686, 1, 1, 0),
(9105422, 0, 11686, 1, 1, 0),
(9105423, 0, 11686, 1, 1, 0),
(9105424, 0, 11686, 1, 1, 0),
(9105425, 0, 11686, 1, 1, 0),
(9105426, 0, 11686, 1, 1, 0),
(9105427, 0, 11686, 1, 1, 0),
(9105428, 0, 11686, 1, 1, 0),
(9105429, 0, 11686, 1, 1, 0),
(9105430, 0, 11686, 1, 1, 0);

-- --- the quests -------------------------------------------------------------------------------------
INSERT INTO `quest_template` (`ID`, `QuestType`, `QuestLevel`, `MinLevel`, `QuestSortID`, `QuestInfoID`, `RewardXPDifficulty`, `RewardMoney`, `Flags`, `AllowableRaces`, `LogTitle`, `LogDescription`, `QuestDescription`, `AreaDescription`, `QuestCompletionLog`, `RequiredNpcOrGo1`, `RequiredNpcOrGoCount1`, `RequiredNpcOrGo2`, `RequiredNpcOrGoCount2`, `RequiredNpcOrGo3`, `RequiredNpcOrGoCount3`, `RequiredNpcOrGo4`, `RequiredNpcOrGoCount4`, `RequiredItemId1`, `RequiredItemCount1`, `RequiredItemId2`, `RequiredItemCount2`, `RequiredItemId3`, `RequiredItemCount3`, `RequiredItemId4`, `RequiredItemCount4`, `RewardItem1`, `RewardAmount1`, `RewardItem2`, `RewardAmount2`, `RewardItem3`, `RewardAmount3`, `RewardItem4`, `RewardAmount4`, `RewardChoiceItemID1`, `RewardChoiceItemQuantity1`, `RewardChoiceItemID2`, `RewardChoiceItemQuantity2`, `RewardChoiceItemID3`, `RewardChoiceItemQuantity3`, `RewardChoiceItemID4`, `RewardChoiceItemQuantity4`, `RewardChoiceItemID5`, `RewardChoiceItemQuantity5`, `RewardChoiceItemID6`, `RewardChoiceItemQuantity6`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `VerifiedBuild`) VALUES
(9105001, 2, 6, 6, 0, 0, 2, 86, 0, 1, 'A Lantern at Home', 'Find Hagatha''s Lantern: south-east of Crystal Lake, Elwynn Forest.', 'You were not born, little horror, you were found. But even a found thing has a place it was found in, and the world remembers you there. I have hung one of my lanterns in Elwynn Forest, south-east of Crystal Lake. Go back the way Wren brought you and look for its light.$B$BWhen you stand beside it, my sister and I will hear you. We will tell you what the beasts there taste of.', '', 'Return to Hagatha''s Lantern (south-east of Crystal Lake, Elwynn Forest).', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', 0),
(9105002, 2, 6, 6, 0, 0, 2, 86, 0, 68, 'A Lantern at Home', 'Find Hagatha''s Lantern: the hills east of Kharanos, Dun Morogh.', 'You were not born, little horror, you were found. But even a found thing has a place it was found in, and the world remembers you there. I have hung one of my lanterns in Dun Morogh, the hills east of Kharanos. Go back the way Wren brought you and look for its light.$B$BWhen you stand beside it, my sister and I will hear you. We will tell you what the beasts there taste of.', '', 'Return to Hagatha''s Lantern (the hills east of Kharanos, Dun Morogh).', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', 0),
(9105003, 2, 6, 6, 0, 0, 2, 86, 0, 8, 'A Lantern at Home', 'Find Hagatha''s Lantern: the woods south-east of Dolanaar, Teldrassil.', 'You were not born, little horror, you were found. But even a found thing has a place it was found in, and the world remembers you there. I have hung one of my lanterns in Teldrassil, the woods south-east of Dolanaar. Go back the way Wren brought you and look for its light.$B$BWhen you stand beside it, my sister and I will hear you. We will tell you what the beasts there taste of.', '', 'Return to Hagatha''s Lantern (the woods south-east of Dolanaar, Teldrassil).', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', 0),
(9105004, 2, 6, 6, 0, 0, 2, 86, 0, 1024, 'A Lantern at Home', 'Find Hagatha''s Lantern: Moongraze Woods, Azuremyst Isle.', 'You were not born, little horror, you were found. But even a found thing has a place it was found in, and the world remembers you there. I have hung one of my lanterns in Azuremyst Isle, Moongraze Woods. Go back the way Wren brought you and look for its light.$B$BWhen you stand beside it, my sister and I will hear you. We will tell you what the beasts there taste of.', '', 'Return to Hagatha''s Lantern (Moongraze Woods, Azuremyst Isle).', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', 0),
(9105005, 2, 6, 6, 0, 0, 2, 86, 0, 130, 'A Lantern at Home', 'Find Hagatha''s Lantern: the scrub west of Razor Hill, Durotar.', 'You were not born, little horror, you were found. But even a found thing has a place it was found in, and the world remembers you there. I have hung one of my lanterns in Durotar, the scrub west of Razor Hill. Go back the way Wren brought you and look for its light.$B$BWhen you stand beside it, my sister and I will hear you. We will tell you what the beasts there taste of.', '', 'Return to Hagatha''s Lantern (the scrub west of Razor Hill, Durotar).', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', 0),
(9105006, 2, 6, 6, 0, 0, 2, 86, 0, 32, 'A Lantern at Home', 'Find Hagatha''s Lantern: the plains north-east of Bloodhoof, Mulgore.', 'You were not born, little horror, you were found. But even a found thing has a place it was found in, and the world remembers you there. I have hung one of my lanterns in Mulgore, the plains north-east of Bloodhoof. Go back the way Wren brought you and look for its light.$B$BWhen you stand beside it, my sister and I will hear you. We will tell you what the beasts there taste of.', '', 'Return to Hagatha''s Lantern (the plains north-east of Bloodhoof, Mulgore).', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', 0),
(9105007, 2, 6, 6, 0, 0, 2, 86, 0, 16, 'A Lantern at Home', 'Find Hagatha''s Lantern: the glades north-west of Brill, Tirisfal Glades.', 'You were not born, little horror, you were found. But even a found thing has a place it was found in, and the world remembers you there. I have hung one of my lanterns in Tirisfal Glades, the glades north-west of Brill. Go back the way Wren brought you and look for its light.$B$BWhen you stand beside it, my sister and I will hear you. We will tell you what the beasts there taste of.', '', 'Return to Hagatha''s Lantern (the glades north-west of Brill, Tirisfal Glades).', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', 0),
(9105008, 2, 6, 6, 0, 0, 2, 86, 0, 512, 'A Lantern at Home', 'Find Hagatha''s Lantern: the woods west of the Dead Scar, Eversong Woods.', 'You were not born, little horror, you were found. But even a found thing has a place it was found in, and the world remembers you there. I have hung one of my lanterns in Eversong Woods, the woods west of the Dead Scar. Go back the way Wren brought you and look for its light.$B$BWhen you stand beside it, my sister and I will hear you. We will tell you what the beasts there taste of.', '', 'Return to Hagatha''s Lantern (the woods west of the Dead Scar, Eversong Woods).', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', 0),
(9105010, 2, 6, 6, 12, 0, 5, 216, 0, 0, 'The Wolves of Elwynn', 'Devour 6 wolves in Elwynn Forest.', 'The lantern''s flame leans toward you, and Hagatha''s voice comes with it, dry as old paper:$B$BThe wolf was the first shape you wore outside the ritual, and you wore it badly. A wolf is not teeth, little horror. A wolf is the pack it runs with. The forests of Elwynn are full of them, mangy and grey and hungry.$B$BEat six of them. Not to kill them, to know them. Then come back and tell me what they tasted of.', '', 'Return to Hagatha''s Lantern (south-east of Crystal Lake, Elwynn Forest).', 9105400, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3511, 1, 23404, 1, 2218, 1, 0, 0, 0, 0, 0, 0, 'Elwynn wolf devoured', '', '', '', 0),
(9105011, 2, 8, 7, 12, 0, 5, 384, 0, 0, 'Wren''s Picnic', 'Devour a Rockhide Boar, a Young Forest Bear and a forest spider in Elwynn Forest.', 'The lantern''s flame leans toward you, and Wren''s voice tumbles out of it, all at once:$B$BSnack! Picnic! I''m packing a basket, a pretend basket, because I can''t come, so you''re eating for both of us. List! One boar, the rocky kind, with the grumpy face. One bear, a young one, they''re softer. And one spider. Don''t make that face, spiders are crunchy and good for you.$B$BEat them all and tell me which one was best. I''m writing it down!', '', 'Return to Hagatha''s Lantern (south-east of Crystal Lake, Elwynn Forest).', 9105401, 1, 9105402, 1, 9105403, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6085, 1, 5617, 1, 3440, 1, 0, 0, 0, 0, 0, 0, 'Rockhide Boar devoured', 'Young Forest Bear devoured', 'Forest or Mine Spider devoured', '', 0),
(9105012, 2, 10, 9, 12, 0, 6, 900, 0, 0, 'Hogger''s Last Supper', 'Devour Hogger at Forest''s Edge in Elwynn Forest.', 'The lantern''s flame leans toward you, and the old voice turns slow, the way it does before a tale:$B$BThe Riverpaw gnolls tell of one of their own who ate so much that the pack could not feed him any more, so they left him at the edge of the forest, and he ate the edge of the forest instead. They call him Hogger. The farmers call him worse.$B$BHe has been the hungriest thing in Elwynn for a long time. Go to Forest''s Edge in the south-west and show him that he is not.', '', 'Return to Hagatha''s Lantern (south-east of Crystal Lake, Elwynn Forest).', 9105404, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1436, 1, 1302, 1, 3581, 1, 0, 0, 0, 0, 0, 0, 'Hogger devoured', '', '', '', 0),
(9105020, 2, 7, 6, 1, 0, 5, 294, 0, 0, 'The Cold Pantry', 'Devour a Snow Leopard, an Ice Claw Bear and a Winter Wolf in Dun Morogh.', 'The lantern''s flame leans toward you, and Wren''s voice crackles through the frost on the glass:$B$BSnack, it''s SO cold where you are. Cold is good for meat, everybody knows that, it keeps. Dun Morogh is basically a big cold pantry. I want you to taste the pantry. One snow leopard, one of the big ice-clawed bears, and one winter wolf.$B$BChew properly. Frozen things crack your teeth if you''re greedy.', '', 'Return to Hagatha''s Lantern (the hills east of Kharanos, Dun Morogh).', 9105405, 1, 9105406, 1, 9105407, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23404, 1, 6085, 1, 2218, 1, 0, 0, 0, 0, 0, 0, 'Snow Leopard devoured', 'Ice Claw Bear devoured', 'Winter Wolf devoured', '', 0),
(9105021, 2, 8, 7, 1, 0, 5, 384, 0, 0, 'Stone in the Belly', 'Devour 6 Rockjaw troggs in Dun Morogh.', 'The lantern''s flame leans toward you, and Hagatha speaks, slow and low:$B$BThe trogg is a strange thing to wear, little horror. It came out of the stone and never forgot it; its skin is half rock, its hunger is all of it. The Rockjaw troggs dig in Gol''Bolar Quarry, south-east of here, and around the lake beyond.$B$BEat six of them. You will feel the stone settle in your belly. That weight is the beginning of the trogg''s strength.', '', 'Return to Hagatha''s Lantern (the hills east of Kharanos, Dun Morogh).', 9105408, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5617, 1, 26051, 1, 4974, 1, 0, 0, 0, 0, 0, 0, 'Rockjaw trogg devoured', '', '', '', 0),
(9105022, 2, 11, 10, 1, 0, 6, 1089, 0, 0, 'The Backbreaker', 'Devour a Rockjaw Backbreaker at Helm''s Bed Lake in Dun Morogh.', 'The lantern''s flame leans toward you, and the flame sinks low, and Hagatha tells it:$B$BThe dwarves tell of a trogg that gnawed on a stone giant''s toe. It never stopped growing harder. Neither did its hunger. Its children still dig at Helm''s Bed Lake, the biggest of the Rockjaw, the ones the dwarves call Backbreakers.$B$BEat one. One is enough to show you what your troggs could become.', '', 'Return to Hagatha''s Lantern (the hills east of Kharanos, Dun Morogh).', 9105409, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2036, 1, 1436, 1, 3570, 1, 0, 0, 0, 0, 0, 0, 'Rockjaw Backbreaker devoured', '', '', '', 0),
(9105030, 2, 6, 6, 141, 0, 5, 216, 0, 0, 'Moonlit Teeth', 'Devour 6 nightsabers in Teldrassil.', 'The lantern''s flame leans toward you, and Hagatha''s voice is soft as moss:$B$BThe nightsaber hunts by moonlight and is never seen until it wants to be. The elves love them. That is the trouble with being loved, little horror: you stop being careful.$B$BEat six of the great cats of Teldrassil. Learn how quiet a hunter can be.', '', 'Return to Hagatha''s Lantern (the woods south-east of Dolanaar, Teldrassil).', 9105410, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23405, 1, 26020, 1, 4974, 1, 0, 0, 0, 0, 0, 0, 'Nightsaber devoured', '', '', '', 0),
(9105031, 2, 7, 7, 141, 0, 5, 294, 0, 0, 'Pellets and Feathers', 'Devour 5 Strigid owls in Teldrassil.', 'The lantern''s flame leans toward you, and Wren''s voice hoots out of it:$B$BHoo! That''s an owl. I do a good owl. Snack, the owls up there, the strigid ones, they swallow mice whole and then they cough up the bones in a little ball. Isn''t that WONDERFUL? You do the same thing but bigger.$B$BEat five of them. If you''re lucky you''ll get their shape too, and then you can hoot back at me.', '', 'Return to Hagatha''s Lantern (the woods south-east of Dolanaar, Teldrassil).', 9105411, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6215, 1, 23404, 1, 3511, 1, 0, 0, 0, 0, 0, 0, 'Strigid owl devoured', '', '', '', 0),
(9105032, 2, 11, 10, 141, 0, 6, 1089, 0, 0, 'The Queen of Webs', 'Devour Lady Sathrah in the Oracle Glade, Teldrassil.', 'The lantern''s flame leans toward you, and Hagatha''s tale comes thin and careful, like thread:$B$BIn the Oracle Glade in the north of the island there is a spider the elves call Lady Sathrah. She eats what the glade''s guardians let fall, and they let a great deal fall. She has grown fat on their kindness and thinks herself a queen.$B$BThere are no queens to a Devourer, little horror. Only meals with longer names.', '', 'Return to Hagatha''s Lantern (the woods south-east of Dolanaar, Teldrassil).', 9105412, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1302, 1, 5327, 1, 3581, 1, 0, 0, 0, 0, 0, 0, 'Lady Sathrah devoured', '', '', '', 0),
(9105040, 2, 6, 6, 3524, 0, 5, 216, 0, 0, 'Long Legs on the Isle', 'Devour 5 timberstriders on Azuremyst Isle.', 'The lantern''s flame leans toward you, and Hagatha speaks:$B$BThe timberstriders of this island are cousins of the plainstriders of Mulgore; the draenei did not bring them, they were here before the crash, picking at the moss. A strider is legs and a beak and a great deal of running away.$B$BEat five. If their shape is not yours yet, it will be.', '', 'Return to Hagatha''s Lantern (Moongraze Woods, Azuremyst Isle).', 9105413, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26018, 1, 24439, 1, 4974, 1, 0, 0, 0, 0, 0, 0, 'Timberstrider devoured', '', '', '', 0),
(9105041, 2, 8, 7, 3524, 0, 5, 384, 0, 0, 'Root Tea', 'Devour 6 Root Trappers and 4 Moongraze deer on Azuremyst Isle.', 'The lantern''s flame leans toward you, and Wren''s voice, muffled, like she has her head in a cupboard:$B$BSnack! I''m out of roots. For tea. Root tea. The roots on your island WALK, which is rude, but it also means you can catch them. Eat six of the root trappers and I''ll brew from whatever''s left in your mouth. Don''t ask how.$B$BAnd four of the moongraze deer while you''re there. For biscuits.', '', 'Return to Hagatha''s Lantern (Moongraze Woods, Azuremyst Isle).', 9105414, 6, 9105415, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26024, 1, 26020, 1, 24343, 1, 0, 0, 0, 0, 0, 0, 'Root Trapper devoured', 'Moongraze deer devoured', '', '', 0),
(9105042, 2, 10, 9, 3524, 0, 6, 900, 0, 0, 'The Moonwing Owlbeasts', 'Devour 3 owlbeasts at the Moonwing Den on Silvermyst Isle.', 'The lantern''s flame leans toward you, and the flame turns the colour of a bruise, and Hagatha tells it:$B$BWhen the draenei ship fell, its broken crystals poisoned the island''s owlbeasts. They gather in the Moonwing Den on Silvermyst Isle, south-west of here, raving. Madness has a taste, little horror. It is sharp, and it stays.$B$BEat three of them. One day you will meet owlbeasts that the moon touched instead of the crystals, and you will know the difference.', '', 'Return to Hagatha''s Lantern (Moongraze Woods, Azuremyst Isle).', 9105416, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26021, 1, 28159, 1, 26052, 1, 0, 0, 0, 0, 0, 0, 'Moonwing owlbeast devoured', '', '', '', 0),
(9105050, 2, 6, 6, 14, 0, 5, 216, 0, 0, 'Tusk and Gristle', 'Devour 6 mottled boars in Durotar.', 'The lantern''s flame leans toward you, and Hagatha''s voice is dry as the dust around it:$B$BThe boar of Durotar eats thorns and stones and anything the orcs leave behind, and it charges at whatever moves. It is not clever. It does not need to be. Some hungers are like that.$B$BEat six of the mottled boars. Taste how little a boar needs to think.', '', 'Return to Hagatha''s Lantern (the scrub west of Razor Hill, Durotar).', 9105417, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24439, 1, 26051, 1, 4947, 1, 0, 0, 0, 0, 0, 0, 'Mottled boar devoured', '', '', '', 0),
(9105051, 2, 8, 7, 14, 0, 5, 384, 0, 0, 'Scales and Stings', 'Devour 4 Bloodtalon raptors and 4 scorpids in Durotar.', 'The lantern''s flame leans toward you, and Wren''s voice, delighted:$B$BSnack, your desert has the BEST snacks. Raptors! Scorpids! Scorpids are like little crabs that hate you. Eat four raptors and four scorpids and tell me which ones bite back harder.$B$BI bet scorpids. I''ve got a whole jar of bets on scorpids.', '', 'Return to Hagatha''s Lantern (the scrub west of Razor Hill, Durotar).', 9105418, 4, 9105419, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5617, 1, 23404, 1, 2218, 1, 0, 0, 0, 0, 0, 0, 'Bloodtalon raptor devoured', 'Durotar scorpid devoured', '', '', 0),
(9105052, 2, 10, 9, 14, 0, 6, 900, 0, 0, 'The Dreadmaw', 'Devour 2 Dreadmaw Crocolisks on the Southfury River in Durotar.', 'The lantern''s flame leans toward you, and Hagatha tells it slow:$B$BThe crocolisks of the Southfury River lie still for days, and the orcs who water their wolves there forget they are there, and then one day they remember. The Dreadmaw, they call them. A thing that waits that long is a thing that is very sure of its hunger.$B$BEat two of them, on the river north of here. Their shape will lie in you like they lie in the water.', '', 'Return to Hagatha''s Lantern (the scrub west of Razor Hill, Durotar).', 9105420, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1436, 1, 28159, 1, 3570, 1, 0, 0, 0, 0, 0, 0, 'Dreadmaw Crocolisk devoured', '', '', '', 0),
(9105060, 2, 6, 6, 215, 0, 5, 216, 0, 0, 'Legs of the Plains', 'Devour 6 plainstriders in Mulgore.', 'The lantern''s flame leans toward you, and Hagatha speaks:$B$BThe tauren say the plainstrider was the Earth Mother''s first runner, sent to carry news across Mulgore before there were tauren to hear it. It still runs, little horror, and it still has no news.$B$BEat six of the grown ones, the adults and the elders.', '', 'Return to Hagatha''s Lantern (the plains north-east of Bloodhoof, Mulgore).', 9105421, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24439, 1, 26018, 1, 4948, 1, 0, 0, 0, 0, 0, 0, 'Plainstrider devoured', '', '', '', 0),
(9105061, 2, 8, 7, 215, 0, 5, 384, 0, 0, 'The Prairie''s Teeth', 'Devour 4 prairie wolves and 3 flatland cougars in Mulgore.', 'The lantern''s flame leans toward you, and Wren''s voice, breathless:$B$BSnack, I was reading about Mulgore and it says there are WOLVES and COUGARS and nobody told me. You could have a wolf shape AND a cat shape. Like hats! Eat four prairie wolves and three of the flatland cougars and you''ll have the whole hat stand.$B$BI''m making you a hat stand. A real one. Hagatha says no.', '', 'Return to Hagatha''s Lantern (the plains north-east of Bloodhoof, Mulgore).', 9105422, 4, 9105423, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5617, 1, 23404, 1, 2218, 1, 0, 0, 0, 0, 0, 0, 'Prairie wolf devoured', 'Flatland cougar devoured', '', '', 0),
(9105062, 2, 10, 9, 215, 0, 6, 900, 0, 0, 'Mazzranache', 'Devour Mazzranache in Mulgore. Hagatha''s Bait, on the Golden Plains, will call it.', 'The lantern''s flame leans toward you, and the flame flickers, and Hagatha tells it:$B$BThe Bloodhoof hunters speak of Mazzranache, a beast of the plains with no herd and no name of its own; they gave it one so they could curse it. It wanders, and it does not come when called. Except by me.$B$BI have left a bait in the grass of the Golden Plains, north-east of Bloodhoof. Touch it, and Mazzranache will come for it. Then eat it. Your striders will remember the taste when they grow.', '', 'Return to Hagatha''s Lantern (the plains north-east of Bloodhoof, Mulgore).', 9105424, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26021, 1, 1436, 1, 26052, 1, 0, 0, 0, 0, 0, 0, 'Mazzranache devoured', '', '', '', 0),
(9105070, 2, 6, 6, 85, 0, 5, 216, 0, 0, 'Wings in the Gloom', 'Devour 6 duskbats in Tirisfal Glades.', 'The lantern''s flame leans toward you, and Hagatha''s voice is almost fond:$B$BThe duskbats of Tirisfal grew fat on what the plague left behind. They are blind, little horror, and they need nothing else. They hear your heart. They hear its hunger.$B$BEat six of them, the greater ones and the vampiric ones. Learn to hear like they do.', '', 'Return to Hagatha''s Lantern (the glades north-west of Brill, Tirisfal Glades).', 9105425, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26020, 1, 4974, 1, 23405, 1, 0, 0, 0, 0, 0, 0, 'Duskbat devoured', '', '', '', 0),
(9105071, 2, 8, 7, 85, 0, 5, 384, 0, 0, 'Hounds of the Glade', 'Devour 6 darkhounds in Tirisfal Glades.', 'The lantern''s flame leans toward you, and Wren''s voice, unusually serious:$B$BSnack, the darkhounds in your glades aren''t dogs. They''re something from the other side of the dark that LOOKS like dogs, which is worse. Hagatha says demons taste like burnt sugar. I want to know if that''s true.$B$BEat six of the cursed and ravenous ones and tell me. For science.', '', 'Return to Hagatha''s Lantern (the glades north-west of Brill, Tirisfal Glades).', 9105426, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5617, 1, 6215, 1, 23404, 1, 0, 0, 0, 0, 0, 0, 'Darkhound devoured', '', '', '', 0),
(9105072, 2, 10, 9, 85, 0, 6, 900, 0, 0, 'The Scarlet Table', 'Devour 5 of the Scarlet Crusade in Tirisfal Glades.', 'The lantern''s flame leans toward you, and Hagatha''s tale comes cold:$B$BThe Scarlet Crusade came to Tirisfal to burn the dead. They have burned a great many things that were not dead yet. They are very sure of themselves, little horror, and sureness is a flavour. It goes well with fear.$B$BEat five of them, at their farms and their watch posts around the glades. A bat that drinks the Scarlet''s blood grows into something the Scarlet have nightmares about.', '', 'Return to Hagatha''s Lantern (the glades north-west of Brill, Tirisfal Glades).', 9105427, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1302, 1, 5327, 1, 3581, 1, 0, 0, 0, 0, 0, 0, 'Scarlet crusader devoured', '', '', '', 0),
(9105080, 2, 6, 6, 3430, 0, 5, 216, 0, 0, 'Spilled Magic', 'Devour 6 mana stalkers or manawraiths at the West Sanctum in Eversong Woods.', 'The lantern''s flame leans toward you, and Hagatha speaks, and the flame hums:$B$BWhen the elves spill their magic, something always laps it up. In the West Sanctum the spill has grown legs: mana stalkers and manawraiths, little whirlwinds of leftover spell. Your mana wyrm would love them.$B$BEat six. Taste what the elves threw away.', '', 'Return to Hagatha''s Lantern (the woods west of the Dead Scar, Eversong Woods).', 9105428, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28149, 1, 24439, 1, 4974, 1, 0, 0, 0, 0, 0, 0, 'Spilled magic devoured', '', '', '', 0),
(9105081, 2, 8, 7, 3430, 0, 5, 384, 0, 0, 'Dragonhawk Down', 'Devour 6 Crazed Dragonhawks in Eversong Woods.', 'The lantern''s flame leans toward you, and Wren''s voice, very fast:$B$BSnack, the elves have DRAGONHAWKS. Little dragons that are also hawks. That''s two snacks in one! The crazed ones are flapping around everywhere and the elves want them gone, so nobody will mind.$B$BEat six. Is it chicken? Tell me if it''s chicken.', '', 'Return to Hagatha''s Lantern (the woods west of the Dead Scar, Eversong Woods).', 9105429, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28147, 1, 5617, 1, 2218, 1, 0, 0, 0, 0, 0, 0, 'Crazed Dragonhawk devoured', '', '', '', 0),
(9105082, 2, 10, 9, 3430, 0, 6, 900, 0, 0, 'The Wretched Feast', 'Devour 6 Wretched in Eversong Woods.', 'The lantern''s flame leans toward you, and Hagatha''s voice is sad and not at all sorry:$B$BThe Wretched were elves who could not stop drinking magic, and now magic is all they are hungry for. They are like you, little horror, except they never learned to be anything else. They haunt Sunsail Anchorage and the shore to the west.$B$BEat six. It is a mercy, of a kind. And a wyrm that eats the Wretched grows into a wraith of pure spell.', '', 'Return to Hagatha''s Lantern (the woods west of the Dead Scar, Eversong Woods).', 9105430, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28142, 1, 28157, 1, 3581, 1, 0, 0, 0, 0, 0, 0, 'Wretched devoured', '', '', '', 0);
INSERT INTO `quest_template_addon` (`ID`, `AllowableClasses`, `PrevQuestID`) VALUES
(9105001, 512, 9101305),
(9105002, 512, 9101305),
(9105003, 512, 9101305),
(9105004, 512, 9101305),
(9105005, 512, 9101305),
(9105006, 512, 9101305),
(9105007, 512, 9101305),
(9105008, 512, 9101305),
(9105010, 512, 0),
(9105011, 512, 9105010),
(9105012, 512, 9105011),
(9105020, 512, 0),
(9105021, 512, 9105020),
(9105022, 512, 9105021),
(9105030, 512, 0),
(9105031, 512, 9105030),
(9105032, 512, 9105031),
(9105040, 512, 0),
(9105041, 512, 9105040),
(9105042, 512, 9105041),
(9105050, 512, 0),
(9105051, 512, 9105050),
(9105052, 512, 9105051),
(9105060, 512, 0),
(9105061, 512, 9105060),
(9105062, 512, 9105061),
(9105070, 512, 0),
(9105071, 512, 9105070),
(9105072, 512, 9105071),
(9105080, 512, 0),
(9105081, 512, 9105080),
(9105082, 512, 9105081);
INSERT INTO `quest_request_items` (`ID`, `EmoteOnComplete`, `EmoteOnIncomplete`, `CompletionText`, `VerifiedBuild`) VALUES
(9105001, 1, 1, 'The lantern is not lit yet? Then you are not there yet, little horror.', 0),
(9105002, 1, 1, 'The lantern is not lit yet? Then you are not there yet, little horror.', 0),
(9105003, 1, 1, 'The lantern is not lit yet? Then you are not there yet, little horror.', 0),
(9105004, 1, 1, 'The lantern is not lit yet? Then you are not there yet, little horror.', 0),
(9105005, 1, 1, 'The lantern is not lit yet? Then you are not there yet, little horror.', 0),
(9105006, 1, 1, 'The lantern is not lit yet? Then you are not there yet, little horror.', 0),
(9105007, 1, 1, 'The lantern is not lit yet? Then you are not there yet, little horror.', 0),
(9105008, 1, 1, 'The lantern is not lit yet? Then you are not there yet, little horror.', 0),
(9105010, 1, 1, 'Six wolves, I said. I can count your meals, little horror. I can smell them on you.', 0),
(9105011, 1, 1, 'The basket''s still pretend-full, Snack. Boar, bear, spider!', 0),
(9105012, 1, 1, 'Hogger is still the hungriest thing in Elwynn. That should bother you more than it does.', 0),
(9105020, 1, 1, 'Pantry''s still full, Snack. Leopard, bear, wolf!', 0),
(9105021, 1, 1, 'Your belly is still light, little horror. Six troggs.', 0),
(9105022, 1, 1, 'The Backbreakers still dig, little horror. One of them, I said.', 0),
(9105030, 1, 1, 'Six cats. They are quiet, but they are not hidden from you.', 0),
(9105031, 1, 1, 'Hoo? Hoo hoo? That means ''still five owls'', Snack.', 0),
(9105032, 1, 1, 'The queen still sits in her web.', 0),
(9105040, 1, 1, 'Five striders, little horror. They run, but not far.', 0),
(9105041, 1, 1, 'No tea yet, Snack. Roots and deer!', 0),
(9105042, 1, 1, 'Three owlbeasts. Their madness keeps them home; go to them.', 0),
(9105050, 1, 1, 'Six boars. They come to you if you stand still long enough.', 0),
(9105051, 1, 1, 'Four and four, Snack! I need it for my bet.', 0),
(9105052, 1, 1, 'They are still lying in the river. Go and remind them.', 0),
(9105060, 1, 1, 'Six striders. They will not stop running for you.', 0),
(9105061, 1, 1, 'Hat stand''s still empty, Snack. Wolves and cougars!', 0),
(9105062, 1, 1, 'Mazzranache still wanders. Touch my bait, little horror; it is there for you.', 0),
(9105070, 1, 1, 'Six bats. Listen for them; they are listening for you.', 0),
(9105071, 1, 1, 'Six hounds, Snack. Science is waiting.', 0),
(9105072, 1, 1, 'Five crusaders. They are easy to find; they shout.', 0),
(9105080, 1, 1, 'Six of them. The West Sanctum hums with them.', 0),
(9105081, 1, 1, 'Six dragonhawks, Snack! I need to know about the chicken.', 0),
(9105082, 1, 1, 'Six of the Wretched. They will not be missed.', 0);
INSERT INTO `quest_offer_reward` (`ID`, `Emote1`, `RewardText`, `VerifiedBuild`) VALUES
(9105001, 1, 'There you are. The flame knew you before I did.$B$BSit, hungry thing. Your home is full of meals, and every meal is a lesson.', 0),
(9105002, 1, 'There you are. The flame knew you before I did.$B$BSit, hungry thing. Your home is full of meals, and every meal is a lesson.', 0),
(9105003, 1, 'There you are. The flame knew you before I did.$B$BSit, hungry thing. Your home is full of meals, and every meal is a lesson.', 0),
(9105004, 1, 'There you are. The flame knew you before I did.$B$BSit, hungry thing. Your home is full of meals, and every meal is a lesson.', 0),
(9105005, 1, 'There you are. The flame knew you before I did.$B$BSit, hungry thing. Your home is full of meals, and every meal is a lesson.', 0),
(9105006, 1, 'There you are. The flame knew you before I did.$B$BSit, hungry thing. Your home is full of meals, and every meal is a lesson.', 0),
(9105007, 1, 'There you are. The flame knew you before I did.$B$BSit, hungry thing. Your home is full of meals, and every meal is a lesson.', 0),
(9105008, 1, 'There you are. The flame knew you before I did.$B$BSit, hungry thing. Your home is full of meals, and every meal is a lesson.', 0),
(9105010, 1, 'Fear, mostly. And rabbit. That is the taste of a wolf that runs alone.$B$BTake something for your trouble. Old things I have kept, and they will fit a shape like yours better than they fit me.', 0),
(9105011, 1, 'The spider was best, wasn''t it? I KNEW it. I''m putting a star next to spider.$B$BHagatha says I have to give you something useful and not another pretend basket. Here!', 0),
(9105012, 1, 'Now you are the hungriest thing in Elwynn. Do not let it go to your head; it is a very small forest.$B$BHere. Wren says these are for heroes. I say they are for whoever ate the hero''s problem.', 0),
(9105020, 1, 'Crunchy? Crunchy. I can hear it in your voice.$B$BHere, Hagatha found these in the cellar. They smell like dwarves. Everything in the cellar smells like dwarves.', 0),
(9105021, 1, 'Heavy, is it? Good. A thing that carries stone inside it does not fall over easily.$B$BTake one of these. Something to wear over the weight.', 0),
(9105022, 1, 'Now you have tasted what a trogg grows into. Remember it: one day your own stone will crack open and something like that will crawl out.$B$BWear this until then.', 0),
(9105030, 1, 'Quiet, were they? You were quieter. That is the lesson.$B$BThese were left in my lantern by someone who did not need them any more.', 0),
(9105031, 1, 'Did you get the shape? Hoot at me. No? Hoot anyway, it''s good practice.$B$BHagatha told me to give you this and to stop hooting. I''ll stop hooting when I''m finished.', 0),
(9105032, 1, 'A long name, and in the end only a meal. Remember that when you meet names longer than hers.$B$BTake your pick. She had no use for them, and neither do I.', 0),
(9105040, 1, 'Long legs. You will want them one day, when something bigger than you is hungry.$B$BTake one of these.', 0),
(9105041, 1, 'Mm, earthy. Hagatha says it tastes like a boot. Hagatha has never tasted a boot, she''s guessing.$B$BHere, a biscuit. Well. Not a biscuit. Better than a biscuit.', 0),
(9105042, 1, 'Sharp, and it stays. Now you know.$B$BThese came out of the wreck. The draenei will not miss them.', 0),
(9105050, 1, 'Tough, and not much else. Do not underestimate ''not much else'', little horror.$B$BHere.', 0),
(9105051, 1, 'Scorpids! I WIN. Hagatha bet raptors. Hagatha has to fold the laundry.$B$BHere''s your share of the winnings.', 0),
(9105052, 1, 'Patient, wasn''t it? That is a crocolisk''s whole secret. Some day the patience will grow teeth, and then more teeth.$B$BTake this, and go north when you are ready.', 0),
(9105060, 1, 'Fast. Stringy. Proud of itself for no reason. A good shape to wear when you need to leave.$B$BTake this.', 0),
(9105061, 1, 'Two new hats! If you didn''t have them already. If you did, then two very full bellies, which is also good.$B$BHagatha said no to the hat stand, so here''s this instead.', 0),
(9105062, 1, 'A beast with a name it never wanted. Now it has no name at all, only you.$B$BWear this. And when your plainstrider is ready to grow, remember the taste.', 0),
(9105070, 1, 'Did you hear them? A heartbeat, a wing, a breath. That is how a bat sees.$B$BTake this.', 0),
(9105071, 1, 'Burnt sugar! She was RIGHT. I hate when she''s right, she does a little smile.$B$BHere, for science.', 0),
(9105072, 1, 'Sure of themselves to the very end. Now you are sure of something too.$B$BTake this, and when your bat is ready to grow, remember the taste of red.', 0),
(9105080, 1, 'Sweet and thin, like the elves. That is the taste of magic without anyone holding it.$B$BTake this.', 0),
(9105081, 1, 'Not chicken. ''Spicy hawk.'' I''ll write that down.$B$BHere, for all the flapping.', 0),
(9105082, 1, 'Hungry things eating hungry things. Do not think about it too long.$B$BTake this, and when your wyrm grows, you will know why I sent you.', 0);
INSERT INTO `creature_queststarter` (`id`, `quest`) VALUES (9101300, 9105001), (9101300, 9105002), (9101300, 9105003), (9101300, 9105004), (9101300, 9105005), (9101300, 9105006), (9101300, 9105007), (9101300, 9105008);
INSERT INTO `gameobject_queststarter` (`id`, `quest`) VALUES (9105000, 9105010), (9105000, 9105011), (9105000, 9105012), (9105001, 9105020), (9105001, 9105021), (9105001, 9105022), (9105002, 9105030), (9105002, 9105031), (9105002, 9105032), (9105003, 9105040), (9105003, 9105041), (9105003, 9105042), (9105004, 9105050), (9105004, 9105051), (9105004, 9105052), (9105005, 9105060), (9105005, 9105061), (9105005, 9105062), (9105006, 9105070), (9105006, 9105071), (9105006, 9105072), (9105007, 9105080), (9105007, 9105081), (9105007, 9105082);
INSERT INTO `gameobject_questender` (`id`, `quest`) VALUES (9105000, 9105001), (9105001, 9105002), (9105002, 9105003), (9105003, 9105004), (9105004, 9105005), (9105005, 9105006), (9105006, 9105007), (9105007, 9105008), (9105000, 9105010), (9105000, 9105011), (9105000, 9105012), (9105001, 9105020), (9105001, 9105021), (9105001, 9105022), (9105002, 9105030), (9105002, 9105031), (9105002, 9105032), (9105003, 9105040), (9105003, 9105041), (9105003, 9105042), (9105004, 9105050), (9105004, 9105051), (9105004, 9105052), (9105005, 9105060), (9105005, 9105061), (9105005, 9105062), (9105006, 9105070), (9105006, 9105071), (9105006, 9105072), (9105007, 9105080), (9105007, 9105081), (9105007, 9105082);
