#!/usr/bin/env python3
"""Writes spell_enums.json: the names of spell effects, auras, targets, mechanics and powers, read from
AzerothCore's headers, so the form editor can show "APPLY_AURA" instead of 6. Run it again only if the core's
lists change (they have not since 3.3.5a):

    python make_spell_enums.py [--core <azerothcore-wotlk>]      default: the core this module sits in
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
HEADERS = {                       # list: (header below the core, enum, prefix the names lose)
    "effects": ("src/server/shared/SharedDefines.h", "SpellEffects", "SPELL_EFFECT_"),
    "targets": ("src/server/shared/SharedDefines.h", "Targets", "TARGET_"),
    "mechanics": ("src/server/shared/SharedDefines.h", "Mechanics", "MECHANIC_"),
    "powers": ("src/server/shared/SharedDefines.h", "Powers", "POWER_"),
    "auras": ("src/server/game/Spells/Auras/SpellAuraDefines.h", "AuraType", "SPELL_AURA_"),
}
SKIP = re.compile(r"^(TOTAL|MAX|NUM)_|_(TOTAL|MAX|COUNT)$|^MAX_")


def read_enum(text: str, enum: str, prefix: str) -> dict[int, str]:
    m = re.search(rf"enum\s+{enum}\b[^{{]*\{{(.*?)\}};", text, re.S)
    if not m:
        raise SystemExit(f"enum {enum} not found")
    out = {}
    for name, value in re.findall(r"^\s*(\w+)\s*=\s*(-?\d+)\s*,?", m.group(1), re.M):
        if SKIP.search(name) or not name.startswith(prefix):
            continue
        out.setdefault(int(value), name[len(prefix):])
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--core", type=Path, default=HERE.parents[3], help="the azerothcore-wotlk checkout")
    a = ap.parse_args()
    out = {"_source": "generated by tools/modeltool/make_spell_enums.py from AzerothCore's SharedDefines.h and "
                      "SpellAuraDefines.h (AGPL, like this module)"}
    for key, (header, enum, prefix) in HEADERS.items():
        values = read_enum((a.core / header).read_text(encoding="utf-8", errors="replace"), enum, prefix)
        out[key] = {str(k): v for k, v in sorted(values.items())}
        print(f"{key}: {len(values)}")
    (HERE / "spell_enums.json").write_text(json.dumps(out, indent=0) + "\n", encoding="utf-8")
    print(f"wrote {HERE / 'spell_enums.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
