#!/usr/bin/env python3
"""Wren's Saddle (the witch race, Quests thread task 020): Wren turns the Devourer into the Derby Beast, a mount the
companion rides on.

    python tools/derby_saddle.py --spell-dbc <server>/data/dbc/Spell.dbc

Writes data/sql/db-world/2026_10_03_01_devourer_derby_saddle.sql (spell_dbc; the client patch reads it from there).
Spell 9103000: 1.5 sec cast, outdoors only, cancelled like a mount (casting or attacking ends it; mechanic Mount);
transform into creature 9101362 (the Derby Beast, the primal tallstrider with its saddle), vehicle 102 (a seat for
the companion), 60% faster. Removed by data/sql/uninstall/world.sql.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
from evolved_kit import spell_rows, CLEAN, NO_MECHANICS, effects, aura, CAST_1500, RANGE_SELF, DUR_INFINITE  # noqa: E402
import evolved_kit  # noqa: E402

OUT_SQL = REPO / "data" / "sql" / "db-world" / "2026_10_03_01_devourer_derby_saddle.sql"
SPELL_WRENS_SADDLE = 9103000
NPC_DERBY_BEAST = 9101362
VEHICLE_SEAT = 102
A_TRANSFORM, A_MOD_INCREASE_SPEED, A_SET_VEHICLE = 56, 31, 296
ATTR0_OUTDOORS_ONLY = 0x00008000
MECHANIC_MOUNT = 21                               # removed by what dismounts
AURA_INTERRUPT_MOUNT_LIKE = 0x4 | 0x1000 | 0x2000   # casting, melee or spell attacks end it, like a mount
TEMPLATE = 458                                    # Brown Horse: a mount's cast, visual and interrupt flags

SADDLE = (SPELL_WRENS_SADDLE, 1, TEMPLATE, {
    **CLEAN, **NO_MECHANICS, "CastingTimeIndex": CAST_1500, "RangeIndex": RANGE_SELF, "DurationIndex": DUR_INFINITE,
    "Attributes": ATTR0_OUTDOORS_ONLY, "RecoveryTime": 0, "SpellIconID": 1176,
    "Mechanic": MECHANIC_MOUNT, "AuraInterruptFlags": AURA_INTERRUPT_MOUNT_LIKE,
    **effects(aura(A_TRANSFORM, 0, NPC_DERBY_BEAST), aura(A_SET_VEHICLE, 0, VEHICLE_SEAT),
              aura(A_MOD_INCREASE_SPEED, 60))},
    ("Wren's Saddle", "Wren's magic turns you into her Derby Beast, saddle and all: a companion can ride on your back, "
     "and you run 60% faster. Outdoors only.", "A Derby Beast with a rider's seat. 60% faster."))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--spell-dbc", required=True, type=Path)
    a = ap.parse_args()
    dbc = evolved_kit.b.Dbc(a.spell_dbc)
    evolved_kit.FIRST, evolved_kit.LAST = SPELL_WRENS_SADDLE, SPELL_WRENS_SADDLE   # spell_rows checks its range
    rows = spell_rows(dbc, [SADDLE])
    b = evolved_kit.b
    sql = ["-- Generated by tools/derby_saddle.py. Do not edit by hand: change the script and run it again.",
           "-- Wren's Saddle (the witch race): transform into the Derby Beast, a seat for the companion, 60% faster.",
           "-- Safe to run again; removed by uninstall/world.sql.", "",
           f"DELETE FROM `spell_dbc` WHERE `ID` = {SPELL_WRENS_SADDLE};",
           "INSERT INTO `spell_dbc` (" + ",".join(f"`{c}`" for c in b.COLUMNS) + ") VALUES",
           ",\n".join(rows) + ";", ""]
    OUT_SQL.write_bytes("\n".join(sql).encode("utf-8"))
    print(f"wrote {OUT_SQL.relative_to(REPO)} (spell {SPELL_WRENS_SADDLE})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
