#!/usr/bin/env python3
"""Task 008: the Devourer's own spellbook tab (a class skill line, like Arms or Fire).

    python tools/spellbook.py

Reads the committed SQL (no client files needed) and writes
    data/sql/db-world/2026_09_30_09_devourer_spellbook.sql
Run it again whenever a Devourer spell, shape or talent is added (e.g. new forms in 2026_09_30_08).

What it writes:
  skillline_dbc            900    "Devourer", SkillLine category 7 (class), the tab's icon = Devour's icon
  skillraceclassinfo_dbc   91000  class 10 may have skill 900 (all races), level range, always at its maximum
  skilllineability_dbc     91001+ one row per Devourer spell, ClassMask 512, AcquireMethod 0 (the skill teaches
                                  nothing by itself; the module and the talents teach the spells as before)
  playercreateinfo_skills         skill 900 for every new Devourer (the module adds it at login when missing)

The client patch (tools/client/build_client_patch.py) puts the same SkillLine, SkillRaceClassInfo and
SkillLineAbility rows into the client's DBCs (it reads every committed 2026_09_30_0*.sql), which is what makes the
client show the tab. tools/build_class_dbc_sql.py checks these ids are free (RESERVED).

Which spells get the tab: Devour, Quick Devour, Rush, Concentrate, every shape's form spell, kit and passive
(devourer_shape), every talent rank (talent_dbc), and the spec spells (BASE_AND_SPEC). Effect helpers (hits,
buffs, meals) and the hidden Anima passive are never in the spellbook and stay out.
Removed by data/sql/uninstall/world.sql (ids above, ClassMask 512) and uninstall/characters.sql (skill 900).
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools" / "client"))
import sqlrows  # noqa: E402

SQL_DIR = REPO / "data" / "sql" / "db-world"
OUT_SQL = SQL_DIR / "2026_09_30_09_devourer_spellbook.sql"

SKILL_DEVOURER = 900                 # SkillLine id (stock 3.3.5a ends below 800; src/Devourer.h SkillDevourer)
SKILL_CATEGORY_CLASS = 7
RCI_ID = 91000                       # SkillRaceClassInfo
SLA_FIRST, SLA_LAST = 91001, 91999   # SkillLineAbility
CLASS_MASK = 512                     # class 10
RCI_FLAGS = 0x10                     # SKILL_FLAG_ALWAYS_MAX_VALUE: the bar is always full, like a class skill
ICON_SPELL = 9100001                 # the tab shows Devour's icon

# Spells outside devourer_shape and talent_dbc that a Devourer has in its spellbook.
BASE_AND_SPEC = {
    9100001: "Devour",
    9100032: "Devour (Quick Devour talent)",
    9100990: "Rush",
    9100992: "Concentrate",
    9100995: "Sniff",
    9100011: "Bottomless Appetite (Glutton)",
    9100012: "Restless Skin (Skinchanger)",
    9100013: "Mother of the Brood (Brood)",
    9100020: "Devour Whole (Glutton)",
    9100034: "Regurgitate (Glutton talent)",
    9100040: "Hatch Brood (Brood)",
    **{9100800 + i: "spec ability (placeholder)" for i in range(9)},
}


def committed() -> list[Path]:
    return sorted(p for p in SQL_DIR.glob("2026_09_30_0*.sql") if ".generated." not in p.name and p != OUT_SQL)


def spellbook_spells(files: list[Path]) -> dict[int, str]:
    """{spell id: where it comes from} for every Devourer spell that belongs on the tab."""
    want = dict(BASE_AND_SPEC)
    for t, cols, rows in (x for f in files for x in sqlrows.inserts(f.read_text(encoding="utf-8"))):
        if t == "devourer_shape":
            for r in rows:
                d = dict(zip(cols, r))
                for c in ("form_spell", "spell_1", "spell_2", "spell_3", "spell_4", "passive"):
                    if d.get(c):
                        want.setdefault(int(d[c]), f"shape {d['shape_id']} {d['name']}: {c}")
        elif t == "talent_dbc":
            for r in rows:
                d = dict(zip(cols, r))
                for c in cols:
                    if c.startswith("SpellRank_") and d[c]:
                        want.setdefault(int(d[c]), f"talent {d['ID']}")
    return want


def q(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "''") + "'"


def main() -> int:
    files = committed()
    spells = sqlrows.table_rows(files, "spell_dbc")
    want = spellbook_spells(files)
    missing = sorted(s for s in want if s not in spells)
    for s in missing:
        print(f"skipped {s} ({want[s]}): no spell_dbc row in the committed SQL", file=sys.stderr)
    ids = sorted(s for s in want if s in spells)
    if len(ids) > SLA_LAST - SLA_FIRST + 1:
        print(f"{len(ids)} spells do not fit SkillLineAbility {SLA_FIRST}-{SLA_LAST}", file=sys.stderr)
        return 1
    icon = int(spells[ICON_SPELL]["SpellIconID"])

    sql = [
        "-- Generated by tools/spellbook.py (task 008). Do not edit by hand: change the script and run it again.",
        "-- The Devourer's own spellbook tab: class skill line 900 and its spells. Safe to run again; removed by",
        f"-- uninstall/world.sql (skill {SKILL_DEVOURER}, SkillRaceClassInfo {RCI_ID}, SkillLineAbility "
        f"{SLA_FIRST}-{SLA_LAST}) and uninstall/characters.sql.",
        "-- The client patch tool copies the three *_dbc tables into the client's DBCs.",
        "",
        f"DELETE FROM `skillline_dbc` WHERE `ID` = {SKILL_DEVOURER};",
        "INSERT INTO `skillline_dbc` (`ID`, `CategoryID`, `SkillCostsID`, `DisplayName_Lang_enUS`, "
        "`DisplayName_Lang_Mask`, `Description_Lang_enUS`, `Description_Lang_Mask`, `SpellIconID`, "
        "`AlternateVerb_Lang_enUS`, `AlternateVerb_Lang_Mask`, `CanLink`) VALUES",
        f"({SKILL_DEVOURER}, {SKILL_CATEGORY_CLASS}, 0, 'Devourer', 16712190, '', 16712190, {icon}, '', 16712190, 0);",
        "",
        f"DELETE FROM `skillraceclassinfo_dbc` WHERE `ID` = {RCI_ID};",
        "INSERT INTO `skillraceclassinfo_dbc` (`ID`, `SkillID`, `RaceMask`, `ClassMask`, `Flags`, `MinLevel`, "
        "`SkillTierID`, `SkillCostIndex`) VALUES",
        f"({RCI_ID}, {SKILL_DEVOURER}, 0, {CLASS_MASK}, {RCI_FLAGS}, 0, 0, 0);",
        "",
        f"DELETE FROM `skilllineability_dbc` WHERE `ID` BETWEEN {SLA_FIRST} AND {SLA_LAST};",
        "INSERT INTO `skilllineability_dbc` (`ID`, `SkillLine`, `Spell`, `RaceMask`, `ClassMask`, `ExcludeRace`, "
        "`ExcludeClass`, `MinSkillLineRank`, `SupercededBySpell`, `AcquireMethod`, `TrivialSkillLineRankHigh`, "
        "`TrivialSkillLineRankLow`, `CharacterPoints_1`, `CharacterPoints_2`) VALUES",
        ",\n".join(f"({SLA_FIRST + i}, {SKILL_DEVOURER}, {s}, 0, {CLASS_MASK}, 0, 0, 0, 0, 0, 0, 0, 0, 0)"
                   for i, s in enumerate(ids)) + ";",
    ]
    sql += [
        "",
        "-- The skill at creation (the module also adds it at login to a Devourer without it).",
        f"DELETE FROM `playercreateinfo_skills` WHERE `classMask` = {CLASS_MASK} AND `skill` = {SKILL_DEVOURER};",
        "INSERT INTO `playercreateinfo_skills` (`raceMask`, `classMask`, `skill`, `rank`, `comment`) VALUES",
        f"(0, {CLASS_MASK}, {SKILL_DEVOURER}, 0, 'Devourer: class skill (spellbook tab)');",
        "",
    ]
    with open(OUT_SQL, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(sql))
    print(f"wrote {OUT_SQL.relative_to(REPO)}: {len(ids)} spells on the Devourer tab, icon {icon}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
