// Generated by tools/witch_sisters.py (task 010) -- change the script and run it again.
#ifndef DEVOURER_SISTERS_IDS_H
#define DEVOURER_SISTERS_IDS_H

#include <cstdint>

namespace Devourer::Sisters
{
    constexpr uint32_t NpcHagatha = 9101300;
    constexpr uint32_t NpcWren = 9101301;
    constexpr uint32_t NpcSnack = 9101302;
    constexpr uint32_t CreditDevoured = 9101310;
    constexpr uint32_t CreditRoar = 9101311;
    constexpr uint32_t CreditTale = 9101312;
    constexpr uint32_t NpcPest = 9101313;
    constexpr uint32_t NpcPestPerched = 9101314;
    constexpr uint32_t CreditPest = 9101315;
    constexpr uint32_t ShapeBiletoad = 14;
    constexpr uint32_t GoCage = 9101300;
    constexpr uint32_t QuestFeeding = 9101301;
    constexpr uint32_t QuestTrick = 9101302;
    constexpr uint32_t QuestTale = 9101303;
    constexpr uint32_t QuestPests = 9101304;
    constexpr uint32_t QuestApprentice = 9101305;   // task 018: the companion joins
    constexpr uint32_t QuestMoltFirst = 9101310;   // task 018: one per evolved form, in order
    constexpr uint32_t QuestMoltLast = 9101343;
    constexpr uint32_t MenuHagatha = 9101300;
    constexpr uint32_t MenuWren = 9101301;
    constexpr uint32_t OptionTale = 3;
    constexpr uint32_t OptionBack = 4;
    constexpr uint32_t OptionShapeTale = 6;   // task 018
    constexpr uint32_t InBetweenMap = 35;
    constexpr float CageX = -98.0f, CageY = 150.0f, CageZ = -40.38f, CageO = 1.5708f;
    constexpr float ArriveX = -98.0f, ArriveY = 143.5f, ArriveZ = -40.38f, ArriveO = 1.5708f;
    constexpr float CageRadius = 2.0f;
    constexpr uint32_t VisualPull = 52233;
    constexpr uint32_t VisualArrive = 61456;
    constexpr uint32_t VisualSleep = 55474;
    constexpr uint32_t VisualTransform = 24085;
    constexpr uint32_t SpellChannel = 40671;

    // Wren's pests: x, y, z, perched (1 = hovering out of reach, only a tongue gets it down)
    struct PestSpot { float X, Y, Z; bool Perched; };
    constexpr PestSpot PestSpots[] =
    {
        { -93.63f, 155.1f, -40.38f, false },
        { -92.0f, 157.0f, -35.38f, true },
        { -106.23f, 158.23f, -40.38f, false },
        { -108.0f, 160.0f, -35.38f, true },
        { -89.77f, 158.23f, -40.38f, false },
        { -88.0f, 160.0f, -35.38f, true },
        { -106.23f, 141.77f, -40.38f, false },
        { -108.0f, 140.0f, -35.38f, true },
        { -89.77f, 141.77f, -40.38f, false },
        { -88.0f, 140.0f, -35.38f, true },
    };

    // creature_text groups
    enum Line : uint8_t
    {
        WrenFoundYou = 0, WrenAwake = 1, WrenBeforeSpell = 2, WrenBaby = 3, WrenChores = 4, WrenSnacks = 5,
        WrenRoar = 6, WrenCageOpen = 7, WrenNoDying = 8, WrenStayIn = 9, WrenWelcomeBack = 10,
        WrenPestSpell = 11, WrenPestToad = 12, WrenPestsGone = 13,
        HagathaHush = 0, HagathaAnother = 1, HagathaBerserker = 2, HagathaTale1 = 3, HagathaTale2 = 4,
        HagathaTale3 = 5, HagathaTale4 = 6, HagathaCageOpen = 7,
        WrenMolt = 14, WrenMoltReady = 15, HagathaMoltFirst = 8,   // task 018 (+ the quest's index)
        HagathaNoTale = 64, WrenApprentice = 29,
    };

    // Task 018: Hagatha's tale of a shape ("Tell me about the shape I wear"), Wren's word on a shape she sees.
    struct ShapeLine { uint32_t Shape; uint8_t Group; };
    constexpr ShapeLine HagathaShapeTales[] =
    {
        { 1, 42 },
        { 2, 43 },
        { 3, 44 },
        { 4, 45 },
        { 5, 46 },
        { 6, 47 },
        { 7, 48 },
        { 8, 49 },
        { 9, 50 },
        { 10, 51 },
        { 11, 52 },
        { 12, 53 },
        { 13, 2 },
        { 14, 54 },
        { 15, 55 },
        { 16, 37 },
        { 17, 9 },
        { 18, 10 },
        { 19, 11 },
        { 20, 12 },
        { 21, 13 },
        { 22, 14 },
        { 23, 15 },
        { 24, 39 },
        { 25, 56 },
        { 26, 40 },
        { 27, 57 },
        { 28, 63 },
        { 29, 18 },
        { 30, 20 },
        { 31, 62 },
        { 32, 19 },
        { 33, 61 },
        { 34, 21 },
        { 35, 60 },
        { 36, 23 },
        { 37, 24 },
        { 38, 59 },
        { 39, 25 },
        { 40, 41 },
        { 41, 58 },
        { 42, 27 },
        { 43, 28 },
        { 44, 29 },
        { 45, 30 },
        { 47, 31 },
        { 48, 32 },
        { 50, 33 },
        { 51, 34 },
        { 52, 35 },
        { 53, 36 },
    };
    constexpr ShapeLine WrenShapeReactions[] =
    {
        { 1, 27 },
        { 2, 21 },
        { 3, 27 },
        { 4, 21 },
        { 5, 16 },
        { 6, 22 },
        { 7, 16 },
        { 8, 18 },
        { 9, 16 },
        { 10, 17 },
        { 11, 19 },
        { 12, 21 },
        { 13, 21 },
        { 14, 20 },
        { 15, 20 },
        { 16, 17 },
        { 17, 16 },
        { 18, 16 },
        { 19, 16 },
        { 20, 22 },
        { 21, 19 },
        { 22, 21 },
        { 23, 18 },
        { 24, 21 },
        { 25, 27 },
        { 26, 27 },
        { 27, 18 },
        { 28, 28 },
        { 29, 28 },
        { 30, 28 },
        { 31, 23 },
        { 32, 23 },
        { 33, 22 },
        { 34, 22 },
        { 35, 26 },
        { 36, 26 },
        { 37, 26 },
        { 38, 25 },
        { 39, 25 },
        { 40, 25 },
        { 41, 24 },
        { 42, 24 },
        { 43, 24 },
        { 44, 26 },
        { 45, 17 },
    };
}

#endif
