// Generated by tools/witch_sisters.py (task 010) -- change the script and run it again.
#ifndef DEVOURER_SISTERS_IDS_H
#define DEVOURER_SISTERS_IDS_H

#include <cstdint>

namespace Devourer::Sisters
{
    constexpr uint32_t NpcHagatha = 9101300;
    constexpr uint32_t NpcWren = 9101301;
    constexpr uint32_t NpcSnack = 9101302;
    constexpr uint32_t CreditDevoured = 9101310;
    constexpr uint32_t CreditRoar = 9101311;
    constexpr uint32_t CreditTale = 9101312;
    constexpr uint32_t GoCage = 9101300;
    constexpr uint32_t QuestFeeding = 9101301;
    constexpr uint32_t QuestTrick = 9101302;
    constexpr uint32_t QuestTale = 9101303;
    constexpr uint32_t MenuHagatha = 9101300;
    constexpr uint32_t MenuWren = 9101301;
    constexpr uint32_t OptionTale = 3;
    constexpr uint32_t OptionBack = 4;
    constexpr uint32_t InBetweenMap = 35;
    constexpr float CageX = -98.0f, CageY = 150.0f, CageZ = -40.28f, CageO = 1.5708f;
    constexpr float ArriveX = -98.0f, ArriveY = 143.5f, ArriveZ = -40.21f, ArriveO = 1.5708f;
    constexpr float CageRadius = 2.0f;
    constexpr uint32_t VisualPull = 52233;
    constexpr uint32_t VisualArrive = 61456;
    constexpr uint32_t VisualSleep = 55474;
    constexpr uint32_t VisualTransform = 24085;

    // creature_text groups
    enum Line : uint8_t
    {
        WrenFoundYou = 0, WrenAwake = 1, WrenBeforeSpell = 2, WrenBaby = 3, WrenChores = 4, WrenSnacks = 5,
        WrenRoar = 6, WrenCageOpen = 7, WrenNoDying = 8, WrenStayIn = 9, WrenWelcomeBack = 10,
        HagathaHush = 0, HagathaAnother = 1, HagathaBerserker = 2, HagathaTale1 = 3, HagathaTale2 = 4,
        HagathaTale3 = 5, HagathaTale4 = 6, HagathaCageOpen = 7,
    };
}

#endif
