// Generated by tools/devourer_quests.py (task 021) -- change the tool and run it again.
#ifndef DEVOURER_QUESTS_IDS_H
#define DEVOURER_QUESTS_IDS_H

#include <cstdint>

namespace Devourer::Quests
{
    enum Event : uint8_t { EventMeal = 1, EventKill = 2 };
    enum Filter : uint8_t { FilterEntry = 1, FilterFamily = 2, FilterType = 3, FilterElite = 4, FilterAny = 5 };

    // An event (a meal, a kill) that fits gives the credit of one quest objective, while the quest is open.
    struct CreditRule { uint32_t Quest; uint32_t Credit; uint8_t Event; uint8_t Filter; uint32_t Value; uint32_t Shapes[4]; };
    constexpr CreditRule CreditRules[] =
    {
        { 9105010, 9105400, EventMeal, FilterFamily, 1, { 0, 0, 0, 0 } },   // The Wolves of Elwynn: Elwynn wolf devoured
        { 9105011, 9105401, EventMeal, FilterEntry, 524, { 0, 0, 0, 0 } },   // Wren's Picnic: Rockhide Boar devoured
        { 9105011, 9105402, EventMeal, FilterEntry, 822, { 0, 0, 0, 0 } },   // Wren's Picnic: Young Forest Bear devoured
        { 9105011, 9105403, EventMeal, FilterEntry, 30, { 0, 0, 0, 0 } },   // Wren's Picnic: Forest or Mine Spider devoured
        { 9105011, 9105403, EventMeal, FilterEntry, 43, { 0, 0, 0, 0 } },   // Wren's Picnic: Forest or Mine Spider devoured
        { 9105012, 9105404, EventMeal, FilterEntry, 448, { 0, 0, 0, 0 } },   // Hogger's Last Supper: Hogger devoured
        { 9105020, 9105405, EventMeal, FilterEntry, 1201, { 0, 0, 0, 0 } },   // The Cold Pantry: Snow Leopard devoured
        { 9105020, 9105406, EventMeal, FilterEntry, 1196, { 0, 0, 0, 0 } },   // The Cold Pantry: Ice Claw Bear devoured
        { 9105020, 9105407, EventMeal, FilterEntry, 1131, { 0, 0, 0, 0 } },   // The Cold Pantry: Winter Wolf devoured
        { 9105021, 9105408, EventMeal, FilterEntry, 1115, { 0, 0, 0, 0 } },   // Stone in the Belly: Rockjaw trogg devoured
        { 9105021, 9105408, EventMeal, FilterEntry, 1116, { 0, 0, 0, 0 } },   // Stone in the Belly: Rockjaw trogg devoured
        { 9105021, 9105408, EventMeal, FilterEntry, 1117, { 0, 0, 0, 0 } },   // Stone in the Belly: Rockjaw trogg devoured
        { 9105021, 9105408, EventMeal, FilterEntry, 1118, { 0, 0, 0, 0 } },   // Stone in the Belly: Rockjaw trogg devoured
        { 9105022, 9105409, EventMeal, FilterEntry, 1118, { 0, 0, 0, 0 } },   // The Backbreaker: Rockjaw Backbreaker devoured
        { 9105030, 9105410, EventMeal, FilterEntry, 2042, { 0, 0, 0, 0 } },   // Moonlit Teeth: Nightsaber devoured
        { 9105030, 9105410, EventMeal, FilterEntry, 2043, { 0, 0, 0, 0 } },   // Moonlit Teeth: Nightsaber devoured
        { 9105030, 9105410, EventMeal, FilterEntry, 2033, { 0, 0, 0, 0 } },   // Moonlit Teeth: Nightsaber devoured
        { 9105030, 9105410, EventMeal, FilterEntry, 2034, { 0, 0, 0, 0 } },   // Moonlit Teeth: Nightsaber devoured
        { 9105031, 9105411, EventMeal, FilterEntry, 1995, { 0, 0, 0, 0 } },   // Pellets and Feathers: Strigid owl devoured
        { 9105031, 9105411, EventMeal, FilterEntry, 1996, { 0, 0, 0, 0 } },   // Pellets and Feathers: Strigid owl devoured
        { 9105031, 9105411, EventMeal, FilterEntry, 1997, { 0, 0, 0, 0 } },   // Pellets and Feathers: Strigid owl devoured
        { 9105032, 9105412, EventMeal, FilterEntry, 7319, { 0, 0, 0, 0 } },   // The Queen of Webs: Lady Sathrah devoured
        { 9105040, 9105413, EventMeal, FilterEntry, 17372, { 0, 0, 0, 0 } },   // Long Legs on the Isle: Timberstrider devoured
        { 9105040, 9105413, EventMeal, FilterEntry, 17373, { 0, 0, 0, 0 } },   // Long Legs on the Isle: Timberstrider devoured
        { 9105040, 9105413, EventMeal, FilterEntry, 17374, { 0, 0, 0, 0 } },   // Long Legs on the Isle: Timberstrider devoured
        { 9105041, 9105414, EventMeal, FilterEntry, 17196, { 0, 0, 0, 0 } },   // Root Tea: Root Trapper devoured
        { 9105041, 9105415, EventMeal, FilterEntry, 17200, { 0, 0, 0, 0 } },   // Root Tea: Moongraze deer devoured
        { 9105041, 9105415, EventMeal, FilterEntry, 17201, { 0, 0, 0, 0 } },   // Root Tea: Moongraze deer devoured
        { 9105042, 9105416, EventMeal, FilterEntry, 17186, { 0, 0, 0, 0 } },   // The Moonwing Owlbeasts: Moonwing owlbeast devoured
        { 9105042, 9105416, EventMeal, FilterEntry, 17187, { 0, 0, 0, 0 } },   // The Moonwing Owlbeasts: Moonwing owlbeast devoured
        { 9105042, 9105416, EventMeal, FilterEntry, 17188, { 0, 0, 0, 0 } },   // The Moonwing Owlbeasts: Moonwing owlbeast devoured
        { 9105050, 9105417, EventMeal, FilterEntry, 3099, { 0, 0, 0, 0 } },   // Tusk and Gristle: Mottled boar devoured
        { 9105050, 9105417, EventMeal, FilterEntry, 3100, { 0, 0, 0, 0 } },   // Tusk and Gristle: Mottled boar devoured
        { 9105050, 9105417, EventMeal, FilterEntry, 3098, { 0, 0, 0, 0 } },   // Tusk and Gristle: Mottled boar devoured
        { 9105051, 9105418, EventMeal, FilterEntry, 3122, { 0, 0, 0, 0 } },   // Scales and Stings: Bloodtalon raptor devoured
        { 9105051, 9105418, EventMeal, FilterEntry, 3123, { 0, 0, 0, 0 } },   // Scales and Stings: Bloodtalon raptor devoured
        { 9105051, 9105419, EventMeal, FilterEntry, 3125, { 0, 0, 0, 0 } },   // Scales and Stings: Durotar scorpid devoured
        { 9105051, 9105419, EventMeal, FilterEntry, 3126, { 0, 0, 0, 0 } },   // Scales and Stings: Durotar scorpid devoured
        { 9105051, 9105419, EventMeal, FilterEntry, 3127, { 0, 0, 0, 0 } },   // Scales and Stings: Durotar scorpid devoured
        { 9105052, 9105420, EventMeal, FilterEntry, 3110, { 0, 0, 0, 0 } },   // The Dreadmaw: Dreadmaw Crocolisk devoured
        { 9105060, 9105421, EventMeal, FilterEntry, 2956, { 0, 0, 0, 0 } },   // Legs of the Plains: Plainstrider devoured
        { 9105060, 9105421, EventMeal, FilterEntry, 2957, { 0, 0, 0, 0 } },   // Legs of the Plains: Plainstrider devoured
        { 9105061, 9105422, EventMeal, FilterEntry, 2958, { 0, 0, 0, 0 } },   // The Prairie's Teeth: Prairie wolf devoured
        { 9105061, 9105422, EventMeal, FilterEntry, 2959, { 0, 0, 0, 0 } },   // The Prairie's Teeth: Prairie wolf devoured
        { 9105061, 9105422, EventMeal, FilterEntry, 2960, { 0, 0, 0, 0 } },   // The Prairie's Teeth: Prairie wolf devoured
        { 9105061, 9105423, EventMeal, FilterEntry, 3035, { 0, 0, 0, 0 } },   // The Prairie's Teeth: Flatland cougar devoured
        { 9105061, 9105423, EventMeal, FilterEntry, 3566, { 0, 0, 0, 0 } },   // The Prairie's Teeth: Flatland cougar devoured
        { 9105062, 9105424, EventMeal, FilterEntry, 3068, { 0, 0, 0, 0 } },   // Mazzranache: Mazzranache devoured
        { 9105070, 9105425, EventMeal, FilterEntry, 1553, { 0, 0, 0, 0 } },   // Wings in the Gloom: Duskbat devoured
        { 9105070, 9105425, EventMeal, FilterEntry, 1554, { 0, 0, 0, 0 } },   // Wings in the Gloom: Duskbat devoured
        { 9105071, 9105426, EventMeal, FilterEntry, 1548, { 0, 0, 0, 0 } },   // Hounds of the Glade: Darkhound devoured
        { 9105071, 9105426, EventMeal, FilterEntry, 1549, { 0, 0, 0, 0 } },   // Hounds of the Glade: Darkhound devoured
        { 9105072, 9105427, EventMeal, FilterEntry, 1535, { 0, 0, 0, 0 } },   // The Scarlet Table: Scarlet crusader devoured
        { 9105072, 9105427, EventMeal, FilterEntry, 1536, { 0, 0, 0, 0 } },   // The Scarlet Table: Scarlet crusader devoured
        { 9105072, 9105427, EventMeal, FilterEntry, 1537, { 0, 0, 0, 0 } },   // The Scarlet Table: Scarlet crusader devoured
        { 9105072, 9105427, EventMeal, FilterEntry, 1538, { 0, 0, 0, 0 } },   // The Scarlet Table: Scarlet crusader devoured
        { 9105072, 9105427, EventMeal, FilterEntry, 1539, { 0, 0, 0, 0 } },   // The Scarlet Table: Scarlet crusader devoured
        { 9105072, 9105427, EventMeal, FilterEntry, 1540, { 0, 0, 0, 0 } },   // The Scarlet Table: Scarlet crusader devoured
        { 9105080, 9105428, EventMeal, FilterEntry, 15647, { 0, 0, 0, 0 } },   // Spilled Magic: Spilled magic devoured
        { 9105080, 9105428, EventMeal, FilterEntry, 15648, { 0, 0, 0, 0 } },   // Spilled Magic: Spilled magic devoured
        { 9105081, 9105429, EventMeal, FilterEntry, 15650, { 0, 0, 0, 0 } },   // Dragonhawk Down: Crazed Dragonhawk devoured
        { 9105082, 9105430, EventMeal, FilterEntry, 15645, { 0, 0, 0, 0 } },   // The Wretched Feast: Wretched devoured
        { 9105082, 9105430, EventMeal, FilterEntry, 16162, { 0, 0, 0, 0 } },   // The Wretched Feast: Wretched devoured
        { 9105082, 9105430, EventMeal, FilterEntry, 15644, { 0, 0, 0, 0 } },   // The Wretched Feast: Wretched devoured
    };

    // Being there: within Radius yards of X, Y on Map.
    struct VisitRule { uint32_t Quest; uint32_t Credit; uint32_t Map; float X, Y, Radius; };
    constexpr VisitRule VisitRules[] =
    {
        { 0, 0, 0, 0.0f, 0.0f, 0.0f },
    };

    // A witch's object (gameobject entry): a token gives the credit of its quest, a lure calls Summon.
    struct UseRule { uint32_t Object; uint32_t Quest; uint32_t Credit; uint32_t Summon; };
    constexpr UseRule UseRules[] =
    {
        { 9105100, 9105062, 0, 3068 },   // Mazzranache: Hagatha's Bait
    };
}

#endif
