// Generated by tools/placeholders.py (task 005) -- keep in step with 2026_09_30_07_devourer_placeholders.sql.
#ifndef DEVOURER_PLACEHOLDER_IDS_H
#define DEVOURER_PLACEHOLDER_IDS_H

#include <cstdint>

namespace Devourer
{
    constexpr uint32_t SpellPlaceholderGlutton20      = 9100800;   // Glutton, level 20: Iron Gut
    constexpr uint32_t SpellPlaceholderGlutton40      = 9100801;   // Glutton, level 40: Devouring Challenge
    constexpr uint32_t SpellPlaceholderGlutton60      = 9100802;   // Glutton, level 60: Last Supper
    constexpr uint32_t SpellPlaceholderSkinchanger20  = 9100803;   // Skinchanger, level 20: Mimic Strike
    constexpr uint32_t SpellPlaceholderSkinchanger40  = 9100804;   // Skinchanger, level 40: Skin Swap
    constexpr uint32_t SpellPlaceholderSkinchanger60  = 9100805;   // Skinchanger, level 60: Form of Many
    constexpr uint32_t SpellPlaceholderBrood20        = 9100806;   // Brood, level 20: Call the Clutch
    constexpr uint32_t SpellPlaceholderBrood40        = 9100807;   // Brood, level 40: Feed the Young
    constexpr uint32_t SpellPlaceholderBrood60        = 9100808;   // Brood, level 60: Brood Swarm
}

#endif
