// Generated by tools/build_devourer_spells.py -- keep in step with the client patch.
#ifndef DEVOURER_SPELL_IDS_H
#define DEVOURER_SPELL_IDS_H

#include <cstdint>

namespace Devourer
{
    constexpr uint32_t SpellDevour                  = 9100001;
    constexpr uint32_t SpellUnlockSethrak           = 9100009;
    constexpr uint32_t SpellUnlockBerserker         = 9100010;
    constexpr uint32_t SpellIdentityGlutton         = 9100011;
    constexpr uint32_t SpellIdentitySkinchanger     = 9100012;
    constexpr uint32_t SpellIdentityBrood           = 9100013;
    constexpr uint32_t SpellDevourWhole             = 9100020;
    constexpr uint32_t SpellGorged                  = 9100021;
    constexpr uint32_t SpellMealMeat                = 9100022;
    constexpr uint32_t SpellMealFlesh               = 9100023;
    constexpr uint32_t SpellMealEssence             = 9100024;
    constexpr uint32_t SpellSated                   = 9100025;
    constexpr uint32_t SpellHatchBrood              = 9100040;
    constexpr uint32_t SpellSethrakForm             = 9100100;
    constexpr uint32_t SpellSethrakChainLightning   = 9100101;
    constexpr uint32_t SpellSethrakCoilStrike       = 9100102;
    constexpr uint32_t SpellSethrakCoilStrikeHit    = 9100103;
    constexpr uint32_t SpellSethrakSandstormShroud  = 9100104;
    constexpr uint32_t SpellSethrakSnakeCharm       = 9100105;
    constexpr uint32_t SpellSethrakRainOfToads      = 9100106;
    constexpr uint32_t SpellSethrakRainOfToadsHit   = 9100107;
    constexpr uint32_t SpellSethrakPlague           = 9100108;
    constexpr uint32_t SpellVashnikForm             = 9100300;
    constexpr uint32_t SpellVashnikStormChain       = 9100301;
    constexpr uint32_t SpellVashnikCoilingWhirl     = 9100302;
    constexpr uint32_t SpellVashnikCoilingWhirlHit  = 9100303;
    constexpr uint32_t SpellVashnikSerpentsGaze     = 9100305;
    constexpr uint32_t SpellVashnikPlagueSwarm      = 9100306;
    constexpr uint32_t SpellVashnikPlagueSwarmHit   = 9100307;
    constexpr uint32_t SpellVashnikRisingSerpents   = 9100308;
    constexpr uint32_t SpellBerserkerForm           = 9100200;
    constexpr uint32_t SpellBerserkerVoidBreath     = 9100201;
    constexpr uint32_t SpellBerserkerStomp          = 9100202;
    constexpr uint32_t SpellBerserkerRoar           = 9100203;
    constexpr uint32_t SpellBerserkerRoarStun       = 9100204;
    constexpr uint32_t SpellBerserkerSmash          = 9100205;
    constexpr uint32_t SpellBerserkerBloodScent     = 9100206;
    constexpr uint32_t SpellBerserkerBloodScentBuff = 9100207;
    constexpr uint32_t SpellMealGrave               = 9100026;
    constexpr uint32_t SpellMealDragon              = 9100027;
    constexpr uint32_t SpellMealDragonBreath        = 9100028;
    constexpr uint32_t SpellMealDemon               = 9100029;
    constexpr uint32_t SpellIndigestion             = 9100030;
    constexpr uint32_t SpellTalentQuickDevour       = 9100031;
    constexpr uint32_t SpellDevourQuick             = 9100032;
    constexpr uint32_t SpellTalentRegurgitate       = 9100033;
    constexpr uint32_t SpellRegurgitate             = 9100034;
    constexpr uint32_t SpellTalentFeast             = 9100035;
    constexpr uint32_t SpellTalentStretchedGut      = 9100036;
    constexpr uint32_t SpellTalentThickHide         = 9100037;
    constexpr uint32_t SpellTalentBileCoating       = 9100038;
    constexpr uint32_t SpellDigestedThickHide       = 9100039;
    constexpr uint32_t SpellDigested                = 9100041;
    constexpr uint32_t SpellDigestedBileCoating     = 9100042;
    constexpr uint32_t SpellBabyForm                = 9100400;
    constexpr uint32_t SpellBabyOverrun             = 9100401;
    constexpr uint32_t SpellBabyOverrunHit          = 9100402;
    constexpr uint32_t SpellBabyGnaw                = 9100403;
    constexpr uint32_t SpellBabyGnawBleed           = 9100404;
    constexpr uint32_t SpellBabyPitifulWail         = 9100405;
    constexpr uint32_t SpellBabyVoidFrenzy          = 9100406;
    constexpr uint32_t SpellBabyVoidFrenzyHit       = 9100407;
    constexpr uint32_t SpellBabyTeething            = 9100408;
    constexpr uint32_t SpellBabyChewed              = 9100409;
}

#endif
