// Generated by tools/placeholders.py (tasks 005, 015) -- keep in step with 2026_09_30_07_devourer_placeholders.sql.
#ifndef DEVOURER_TALENT_IDS_H
#define DEVOURER_TALENT_IDS_H

#include <cstdint>

namespace Devourer
{
    // A talent's rank spells are consecutive: rank r is First + r - 1 (Mgr::Rank).
    struct TalentRef { uint32_t First; uint8_t Ranks; };

    // spec abilities
    constexpr uint32_t SpellIronGut                   = 9100800;   // Glutton, level 20: Iron Gut
    constexpr uint32_t SpellDevouringChallenge        = 9100801;   // Glutton, level 40: Devouring Challenge
    constexpr uint32_t SpellLastSupper                = 9100802;   // Glutton, level 60: Last Supper
    constexpr uint32_t SpellMimicStrike               = 9100803;   // Skinchanger, level 20: Mimic Strike
    constexpr uint32_t SpellSkinSwap                  = 9100804;   // Skinchanger, level 40: Skin Swap
    constexpr uint32_t SpellFormOfMany                = 9100805;   // Skinchanger, level 60: Form of Many
    constexpr uint32_t SpellCallTheClutch             = 9100806;   // Brood, level 20: Call the Clutch
    constexpr uint32_t SpellFeedTheYoung              = 9100807;   // Brood, level 40: Feed the Young
    constexpr uint32_t SpellBroodSwarm                = 9100808;   // Brood, level 60: Brood Swarm

    // active talents
    constexpr uint32_t SpellStolenInstinct               = 9100594;   // active talent: Stolen Instinct
    constexpr uint32_t SpellEchoFlesh                    = 9100618;   // active talent: Echo Flesh
    constexpr uint32_t SpellWornFaces                    = 9100630;   // active talent: Worn Faces
    constexpr uint32_t SpellNestGuard                    = 9100684;   // active talent: Nest Guard
    constexpr uint32_t SpellBroodSense                   = 9100708;   // active talent: Brood Sense
    constexpr uint32_t SpellNestScent                    = 9100720;   // active talent: Nest Scent

    // helper spells
    constexpr uint32_t SpellNatureA                   = 9101030;   // Devourer's Nature
    constexpr uint32_t SpellNatureB                   = 9101031;   // Devourer's Nature
    constexpr uint32_t SpellNatureC                   = 9101032;   // Devourer's Nature
    constexpr uint32_t SpellHide                      = 9101033;   // Devourer's Hide
    constexpr uint32_t SpellStoneStomach              = 9101034;   // Stomach of Stone
    constexpr uint32_t SpellIronGutBuff               = 9101035;   // Iron Gut
    constexpr uint32_t SpellChallenged                = 9101036;   // Devouring Challenge
    constexpr uint32_t SpellCrushingJaw               = 9101037;   // Crushing Jaw
    constexpr uint32_t SpellSlowChew                  = 9101038;   // Slow Chew
    constexpr uint32_t SpellFatReserves               = 9101039;   // Fat Reserves
    constexpr uint32_t SpellClutchCall                = 9101040;   // Call the Clutch
    constexpr uint32_t SpellFedYoung                  = 9101041;   // Fed Young
    constexpr uint32_t SpellNestWeb                   = 9101042;   // Nest Web
    constexpr uint32_t SpellNestScentMark             = 9101043;   // Nest Scent
    constexpr uint32_t SpellYoungTeeth                = 9101044;   // Young Teeth
    constexpr uint32_t SpellEggburst                  = 9101045;   // Eggburst
    constexpr uint32_t SpellThickShells               = 9101046;   // Thick Shells
    constexpr uint32_t SpellPetBond                   = 9101047;   // Pet Bond

    // marker talents (the module reads their rank)
    constexpr TalentRef TalIronStomach           { 9100050, 5 };   // Iron Stomach
    constexpr TalentRef TalDeepHunger            { 9100055, 5 };   // Deep Hunger
    constexpr TalentRef TalThickGullet           { 9100500, 3 };   // Thick Gullet
    constexpr TalentRef TalIronMaw               { 9100503, 2 };   // Iron Maw
    constexpr TalentRef TalBottomlessPit         { 9100505, 5 };   // Bottomless Pit
    constexpr TalentRef TalGristlePlating        { 9100510, 3 };   // Gristle Plating
    constexpr TalentRef TalHeavyBelly            { 9100513, 5 };   // Heavy Belly
    constexpr TalentRef TalBloatedResolve        { 9100518, 2 };   // Bloated Resolve
    constexpr TalentRef TalDigestiveFire         { 9100520, 3 };   // Digestive Fire
    constexpr TalentRef TalSlowChew              { 9100523, 5 };   // Slow Chew
    constexpr TalentRef TalGrandAppetite         { 9100528, 1 };   // Grand Appetite
    constexpr TalentRef TalChewingCud            { 9100529, 3 };   // Chewing Cud
    constexpr TalentRef TalSwallowedPride        { 9100532, 3 };   // Swallowed Pride
    constexpr TalentRef TalBellyOfTheBeast       { 9100535, 3 };   // Belly of the Beast
    constexpr TalentRef TalRavenousGuard         { 9100538, 2 };   // Ravenous Guard
    constexpr TalentRef TalFatReserves           { 9100540, 1 };   // Fat Reserves
    constexpr TalentRef TalGnawingPatience       { 9100541, 5 };   // Gnawing Patience
    constexpr TalentRef TalCrushingJaw           { 9100546, 2 };   // Crushing Jaw
    constexpr TalentRef TalSatiation             { 9100548, 3 };   // Satiation
    constexpr TalentRef TalHungersWall           { 9100551, 3 };   // Hunger's Wall
    constexpr TalentRef TalUnendingMeal          { 9100554, 5 };   // Unending Meal
    constexpr TalentRef TalGluttonsBulk          { 9100559, 3 };   // Glutton's Bulk
    constexpr TalentRef TalStomachOfStone        { 9100562, 1 };   // Stomach of Stone
    constexpr TalentRef TalFluidFlesh            { 9100060, 5 };   // Fluid Flesh
    constexpr TalentRef TalShiftingHide          { 9100563, 5 };   // Shifting Hide
    constexpr TalentRef TalBorrowedClaws         { 9100568, 3 };   // Borrowed Claws
    constexpr TalentRef TalQuickMolt             { 9100571, 3 };   // Quick Molt
    constexpr TalentRef TalSecondSkin            { 9100574, 5 };   // Second Skin
    constexpr TalentRef TalMimicsEye             { 9100579, 2 };   // Mimic's Eye
    constexpr TalentRef TalRestlessForm          { 9100581, 3 };   // Restless Form
    constexpr TalentRef TalShedSkin              { 9100584, 2 };   // Shed Skin
    constexpr TalentRef TalManyFaces             { 9100586, 3 };   // Many Faces
    constexpr TalentRef TalLooseBones            { 9100589, 5 };   // Loose Bones
    constexpr TalentRef TalChangingBlood         { 9100595, 5 };   // Changing Blood
    constexpr TalentRef TalFlickerShape          { 9100600, 3 };   // Flicker Shape
    constexpr TalentRef TalMaskOfMeat            { 9100603, 5 };   // Mask of Meat
    constexpr TalentRef TalShapeMemory           { 9100608, 2 };   // Shape Memory
    constexpr TalentRef TalWanderingSkin         { 9100610, 3 };   // Wandering Skin
    constexpr TalentRef TalUnfixedNature         { 9100613, 5 };   // Unfixed Nature
    constexpr TalentRef TalLivingMask            { 9100619, 3 };   // Living Mask
    constexpr TalentRef TalSkinHoard             { 9100622, 3 };   // Skin Hoard
    constexpr TalentRef TalSwiftChange           { 9100625, 3 };   // Swift Change
    constexpr TalentRef TalHollowShell           { 9100628, 2 };   // Hollow Shell
    constexpr TalentRef TalBorrowedVoice         { 9100631, 5 };   // Borrowed Voice
    constexpr TalentRef TalSoftBones             { 9100636, 2 };   // Soft Bones
    constexpr TalentRef TalShapelessStep         { 9100638, 3 };   // Shapeless Step
    constexpr TalentRef TalMirrorHunger          { 9100641, 3 };   // Mirror Hunger
    constexpr TalentRef TalStolenStrength        { 9100644, 5 };   // Stolen Strength
    constexpr TalentRef TalFleetingForm          { 9100649, 3 };   // Fleeting Form
    constexpr TalentRef TalThousandSkins         { 9100652, 1 };   // Thousand Skins
    constexpr TalentRef TalSwellingBrood         { 9100065, 5 };   // Swelling Brood
    constexpr TalentRef TalWarmNest              { 9100653, 5 };   // Warm Nest
    constexpr TalentRef TalEggTooth              { 9100658, 3 };   // Egg Tooth
    constexpr TalentRef TalManyMouths            { 9100661, 3 };   // Many Mouths
    constexpr TalentRef TalNursingHunger         { 9100664, 5 };   // Nursing Hunger
    constexpr TalentRef TalSharedMeal            { 9100669, 2 };   // Shared Meal
    constexpr TalentRef TalHatchingHeat          { 9100671, 3 };   // Hatching Heat
    constexpr TalentRef TalBroodMother           { 9100674, 2 };   // Brood Mother
    constexpr TalentRef TalClutchInstinct        { 9100676, 3 };   // Clutch Instinct
    constexpr TalentRef TalHungryYoung           { 9100679, 5 };   // Hungry Young
    constexpr TalentRef TalFeedingFrenzy         { 9100685, 5 };   // Feeding Frenzy
    constexpr TalentRef TalSpawningPool          { 9100690, 3 };   // Spawning Pool
    constexpr TalentRef TalLitterBond            { 9100693, 5 };   // Litter Bond
    constexpr TalentRef TalTwitchingEggs         { 9100698, 2 };   // Twitching Eggs
    constexpr TalentRef TalSwarmCall             { 9100700, 3 };   // Swarm Call
    constexpr TalentRef TalNestWeb               { 9100703, 5 };   // Nest Web
    constexpr TalentRef TalThickShells           { 9100709, 3 };   // Thick Shells
    constexpr TalentRef TalQuickHatching         { 9100712, 3 };   // Quick Hatching
    constexpr TalentRef TalBloodMilk             { 9100715, 3 };   // Blood Milk
    constexpr TalentRef TalSwollenSac            { 9100718, 2 };   // Swollen Sac
    constexpr TalentRef TalHiveMind              { 9100721, 5 };   // Hive Mind
    constexpr TalentRef TalYoungTeeth            { 9100726, 2 };   // Young Teeth
    constexpr TalentRef TalCrawlingMass          { 9100728, 3 };   // Crawling Mass
    constexpr TalentRef TalMothersWrath          { 9100731, 3 };   // Mother's Wrath
    constexpr TalentRef TalEndlessClutch         { 9100734, 5 };   // Endless Clutch
    constexpr TalentRef TalSwarmTide             { 9100739, 3 };   // Swarm Tide
    constexpr TalentRef TalQueenOfTheBrood       { 9100742, 1 };   // Queen of the Brood
}

#endif
